import type { CaricoCamion, EventoCarico } from "../models/Loading";
import type { Pacco, UnitaSingola } from "../models/Scanning";
import type { Commessa, Pannello } from "../types/excel";

export const shipmentDate=(load:CaricoCamion)=>load.eventi.filter(e=>e.tipo==="PARTENZA").at(-1)?.dataOra??load.completatoIl??load.avviatoIl;
export const shippedLoads=(loads:CaricoCamion[])=>loads.filter(load=>load.stato==="SPEDITO").sort((a,b)=>shipmentDate(b).localeCompare(shipmentDate(a)));
export function loadPackages(load:CaricoCamion,packs:Pacco[]){const codes=new Set(load.scansioni.filter(s=>s.tipoUnita==="PACCO").map(s=>s.codiceUnita));return packs.filter(p=>p.commessa===load.commessa&&p.camion===load.camion&&codes.has(p.codice));}
export function loadSingles(load:CaricoCamion,singles:UnitaSingola[],commesse:Commessa[],packs:Pacco[]):Array<{unit:UnitaSingola;panel:Pannello}>{const codes=new Set(load.scansioni.filter(s=>s.tipoUnita==="SINGOLO").map(s=>s.codiceUnita));const children=new Set(loadPackages(load,packs).flatMap(p=>p.pannelli.map(x=>x.numeroPannello)));const order=commesse.find(c=>c.ordine===load.commessa);return singles.flatMap(unit=>{const panel=order?.pannelli.find(p=>p.numeroCamion===load.camion&&p.numeroPannello===unit.numeroPannello);return codes.has(unit.numeroPannello)&&!children.has(unit.numeroPannello)&&panel?[{unit,panel}]:[];});}
export function totals(load:CaricoCamion,packs:Pacco[],singles:UnitaSingola[],commesse:Commessa[]){const ps=loadPackages(load,packs),ss=loadSingles(load,singles,commesse,packs);return{panels:ps.reduce((n,p)=>n+p.numeroPezzi,0)+ss.length,packs:ps.length,weight:ps.reduce((n,p)=>n+p.pesoTotale,0)+ss.reduce((n,x)=>n+x.panel.peso,0),volume:ps.reduce((n,p)=>n+p.volumeTotale,0)+ss.reduce((n,x)=>n+x.panel.volume,0)};}
export function timeline(load:CaricoCamion):EventoCarico[]{const scans:EventoCarico[]=load.scansioni.map(s=>({tipo:"SCANSIONE",dataOra:s.dataOra,operatoreId:s.operatoreId,operatore:s.operatore,nota:`${s.tipoUnita} ${s.codiceUnita}`}));return[...load.eventi,...scans].sort((a,b)=>b.dataOra.localeCompare(a.dataOra));}
export function matchesHistory(load:CaricoCamion,query:string,packs:Pacco[]){const q=query.trim().toLocaleLowerCase("it");if(!q)return true;const values=[load.commessa,load.cliente,load.camion,load.trasportatoreId,load.rimorchioId,...load.scansioni.map(s=>s.codiceUnita),...loadPackages(load,packs).flatMap(p=>[p.codice,...p.pannelli.map(x=>x.numeroPannello)])];return values.some(v=>v?.toLocaleLowerCase("it").includes(q));}
export function exportHistoryCsv(loads:CaricoCamion[],packs:Pacco[],singles:UnitaSingola[],commesse:Commessa[],carrier:(id?:string)=>string,trailer:(id?:string)=>string){const rows=loads.map(l=>{const t=totals(l,packs,singles,commesse);return[shipmentDate(l),l.commessa,l.cliente,l.camion,carrier(l.trasportatoreId),trailer(l.rimorchioId),t.panels,t.packs,t.weight.toFixed(1),t.volume.toFixed(3),l.operatore].map(csv).join(";");});return["Data spedizione;Commessa;Cliente;Camion;Trasportatore;Rimorchio;Pannelli;Pacchi;Peso;Volume;Operatori",...rows].join("\r\n");}
const csv=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
