import type{CaricoCamion}from"../models/Loading";import{apiRequest}from"./apiClient";
interface ApiUnit{id:string;unitType:"PANEL"|"PACKAGE";panelId:string|null;packageId:string|null;code:string;weight:number;volume:number;loadedAt:string;loadedByOperatorId:string;}
export interface ApiSession{id:string;loadId:string;commessa:string;cliente:string;camion:string;stato:CaricoCamion["stato"];operatorId:string;destinationType:"RIMORCHIO_ESSEPI"|"TRASPORTATORE";trailerId:string|null;carrierId:string|null;startedAt:string;completedAt:string|null;reopenedAt:string|null;shippedAt:string|null;units:ApiUnit[];events:Array<{type:string;operatorId:string|null;timestamp:string;note:string|null}>;}
export interface LoadingSettings{operatorId:string;destinationType:"RIMORCHIO_ESSEPI"|"TRASPORTATORE";trailerId?:string;carrierId?:string}
const eventType=(type:string):"AVVIO"|"UNITA_AGGIUNTA"|"UNITA_RIMOSSA"|"CHIUSURA"|"RIAPERTURA"|"PARTENZA"=>type==="LOADING_STARTED"?"AVVIO":type==="UNIT_LOADED"?"UNITA_AGGIUNTA":type==="UNIT_UNLOADED"?"UNITA_RIMOSSA":type==="LOADING_COMPLETED"?"CHIUSURA":type==="LOADING_REOPENED"?"RIAPERTURA":"PARTENZA";
const toLoad=(s:ApiSession,operatorName:(id:string)=>string):CaricoCamion=>({loadId:s.id,backendLoadId:s.loadId,commessa:s.commessa,cliente:s.cliente,camion:s.camion,stato:s.stato,tipoDestinazione:s.destinationType,...(s.trailerId?{rimorchioId:s.trailerId}:{}),...(s.carrierId?{trasportatoreId:s.carrierId}:{}),operatoreId:s.operatorId,operatore:operatorName(s.operatorId),avviatoIl:s.startedAt,...(s.completedAt?{completatoIl:s.completedAt}:{}),...(s.shippedAt?{speditoIl:s.shippedAt}:{}),scansioni:s.units.map(u=>({unitId:u.id,...(u.panelId?{panelId:u.panelId}:{}),...(u.packageId?{packageId:u.packageId}:{}),tipoUnita:u.unitType==="PANEL"?"SINGOLO":"PACCO",codiceUnita:u.code,commessa:s.commessa,camion:s.camion,operatoreId:u.loadedByOperatorId,operatore:operatorName(u.loadedByOperatorId),dataOra:u.loadedAt,peso:u.weight,volume:u.volume,esito:"OK"})),eventi:s.events.map(event=>({tipo:eventType(event.type),dataOra:event.timestamp,operatoreId:event.operatorId??s.operatorId,operatore:operatorName(event.operatorId??s.operatorId),...(event.note?{nota:event.note}:{})}))});
export const listLoadingSessions=async(operatorName:(id:string)=>string)=>{const data=await apiRequest<ApiSession[]>("/loading-sessions");return data.map(s=>toLoad(s,operatorName));};
export const createLoadingSession=(loadId:string,input:LoadingSettings)=>apiRequest<ApiSession>(`/loads/${loadId}/loading-session`,{method:"POST",body:JSON.stringify(input)});
export const updateLoadingSession=(id:string,input:LoadingSettings)=>apiRequest<ApiSession>(`/loading-sessions/${id}`,{method:"PATCH",body:JSON.stringify(input)});
export const loadUnitApi=(id:string,input:{unitType:"PANEL"|"PACKAGE";panelId?:string;packageId?:string;operatorId:string})=>apiRequest<ApiSession>(`/loading-sessions/${id}/units`,{method:"POST",body:JSON.stringify(input)});
export const unloadUnitApi=(id:string,unitId:string,operatorId:string)=>apiRequest<ApiSession>(`/loading-sessions/${id}/units/${unitId}`,{method:"DELETE",body:JSON.stringify({operatorId})});
export const completeLoadingApi=(id:string)=>apiRequest<ApiSession>(`/loading-sessions/${id}/complete`,{method:"POST"});
export const reopenLoadingApi=(id:string,note?:string)=>apiRequest<ApiSession>(`/loading-sessions/${id}/reopen`,{method:"POST",body:JSON.stringify({note})});
export const shipLoadingApi=(id:string,carrierId:string)=>apiRequest<ApiSession>(`/loading-sessions/${id}/ship`,{method:"POST",body:JSON.stringify({carrierId})});
