import type { Commessa,Pannello } from "../types/excel";
import { apiRequest } from "./apiClient";
import { normalizeOrder } from "../utils/loadIdentity";

type LoadStatus="DA_COMPLETARE"|"DA_CARICARE"|"IN_CARICO"|"ATTESA_SPEDIZIONE"|"SPEDITO";
type PanelStatus="MANCANTE"|"IN_LAVORAZIONE_PACCO"|"DISPONIBILE"|"CARICATO"|"SPEDITO";
export interface ApiPanel{id:string;loadId:string;commessa?:string;numeroPannello:string;numeroCliente:string;numeroMasterPanel:string;camion:string;lato1:string;lato2:string;tipoPannello:string;quantita:number;spessore:number;lunghezza:number;altezza:number;superficie:number;volume:number;peso:number;stato:PanelStatus;packageId:string|null;manualLocation:string|null;scannedAt:string|null;scannedByOperatorId:string|null;createdAt:string;updatedAt:string;}
interface ApiLoad{id:string;commessa:string;cliente:string;numeroCliente:string;riferimentoOrdine:string;camion:string;stato:LoadStatus;createdAt:string;updatedAt:string;pannelli:ApiPanel[];}
interface ImportBody{commessa:string;cliente:string;numeroCliente:string;riferimentoOrdine:string;removeMissing?:boolean;pannelli:Array<Omit<ApiPanel,"id"|"loadId"|"commessa"|"stato"|"packageId"|"manualLocation"|"scannedAt"|"scannedByOperatorId"|"createdAt"|"updatedAt">>;}

export const toPanel=(panel:ApiPanel):Pannello=>({backendId:panel.id,loadId:panel.loadId,...(panel.packageId?{packageId:panel.packageId}:{}),...(panel.manualLocation?{manualLocation:panel.manualLocation}:{}),...(panel.scannedAt?{scannedAt:panel.scannedAt}:{}),...(panel.scannedByOperatorId?{scannedByOperatorId:panel.scannedByOperatorId}:{}),numeroPannello:panel.numeroPannello,numeroCliente:panel.numeroCliente,numeroMasterPanel:panel.numeroMasterPanel,numeroCamion:panel.camion,lato1:panel.lato1,lato2:panel.lato2,tipoPannello:panel.tipoPannello,quantita:panel.quantita,spessore:panel.spessore,lunghezza:panel.lunghezza,altezza:panel.altezza,superficie:panel.superficie,volume:panel.volume,peso:panel.peso,preparato:panel.stato!=="MANCANTE",caricato:panel.stato==="CARICATO"||panel.stato==="SPEDITO",spedito:panel.stato==="SPEDITO"});
const toBody=(commessa:Commessa,panels=commessa.pannelli,removeMissing?:boolean):ImportBody=>({commessa:commessa.ordine,cliente:commessa.cliente,numeroCliente:commessa.numeroCliente,riferimentoOrdine:commessa.riferimento,...(removeMissing===undefined?{}:{removeMissing}),pannelli:panels.map(panel=>({numeroPannello:panel.numeroPannello,numeroCliente:panel.numeroCliente,numeroMasterPanel:panel.numeroMasterPanel,camion:panel.numeroCamion,lato1:panel.lato1,lato2:panel.lato2,tipoPannello:panel.tipoPannello,quantita:panel.quantita,spessore:panel.spessore,lunghezza:panel.lunghezza,altezza:panel.altezza,superficie:panel.superficie,volume:panel.volume,peso:panel.peso}))});
const compose=(loads:ApiLoad[]):Commessa[]=>{const grouped=new Map<string,Commessa>();for(const load of loads){const key=normalizeOrder(load.commessa);const existing=grouped.get(key);if(existing)existing.pannelli.push(...load.pannelli.map(toPanel));else grouped.set(key,{ordine:load.commessa,cliente:load.cliente,numeroCliente:load.numeroCliente,riferimento:load.riferimentoOrdine,pannelli:load.pannelli.map(toPanel)});}return[...grouped.values()];};
export const fetchLoads=():Promise<ApiLoad[]>=>apiRequest<ApiLoad[]>("/loads");
export const loadCommesseFromApi=async():Promise<Commessa[]>=>compose(await fetchLoads());
export const importCommessaToApi=async(commessa:Commessa):Promise<Commessa[]>=>{await apiRequest<ApiLoad[]>("/loads/import",{method:"POST",body:JSON.stringify(toBody(commessa))});return loadCommesseFromApi();};
export const updateCommessaInApi=async(commessa:Commessa,removeMissing:boolean):Promise<Commessa[]>=>{await apiRequest<ApiLoad[]>(`/orders/${encodeURIComponent(commessa.ordine)}/import`,{method:"PUT",body:JSON.stringify(toBody(commessa,commessa.pannelli,removeMissing))});return loadCommesseFromApi();};
export const deleteCommessaFromApi=async(ordine:string,confirmPlanning=false):Promise<void>=>{const query=confirmPlanning?"?confirmPlanning=true":"";await apiRequest<void>(`/orders/${encodeURIComponent(ordine)}${query}`,{method:"DELETE"});};
