import * as XLSX from "xlsx";
import { documentReference,type PreparedShipmentDocument } from "./shipmentDocumentModel";
// Excel dates preserve the local calendar fields, independently of the browser timezone.
const excelDate=(value:string|null)=>{if(!value)return null;const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Rome",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));const get=(type:string)=>Number(parts.find(p=>p.type===type)?.value);return (Date.UTC(get('year'),get('month')-1,get('day'),get('hour'),get('minute'),get('second'))-Date.UTC(1899,11,30))/86400000;};
export function createShipmentWorkbook(model:PreparedShipmentDocument){
 const workbook=XLSX.utils.book_new();const end=model.elements.length+1;
 const summary:XLSX.WorkSheet=XLSX.utils.aoa_to_sheet([
  ['SCHEDA SPEDIZIONE',''],['Identificativo spedizione',model.shipmentId],['Commessa',model.order],['Cliente',model.customer],['Camion',model.truck],['Data spedizione',excelDate(model.shippedAt)],['Prima data prevista certificata',excelDate(model.firstPlannedDate)],['Modalità trasporto',model.transport],['Dettaglio trasporto',model.transportDetail??'—'],['Trasportatore',documentReference(model.carrier)],['Rimorchio',model.trailer?`${model.trailer.plate} - ${documentReference(model.trailer)}`:'—'],['Operatore avvio',documentReference(model.operators.start)],['Operatore chiusura',documentReference(model.operators.close)],['Operatore partenza',documentReference(model.operators.departure)],['Elementi previsti',model.totals.expected],['Elementi spediti',model.totals.shipped],['Pacchi spediti',model.totals.packages],['Peso totale (kg)',model.totals.weight],['Volume totale (m³)',model.totals.volume],['Permanenza in magazzino (gg)',model.totals.warehouseDays],['Documento operativo','Non costituisce un DDT ufficiale'],...model.warnings.flatMap(w=>(w.match(/.{1,90}(?:\s|$)|.{1,90}/g)??[w]).map((line,i)=>[i===0?'Informazioni storiche':'',line.trim()]))
 ]);
 summary.B6.z='dd/mm/yyyy';if(summary.B7)summary.B7.z='dd/mm/yyyy';summary.B18={t:'n',v:model.totals.weight,f:`SUM('Elementi spediti'!J2:J${end})`,z:'#,##0.0'};summary.B19={t:'n',v:model.totals.volume,f:`SUM('Elementi spediti'!K2:K${end})`,z:'#,##0.000'};
 summary['!cols']=[{wch:35},{wch:95}];summary['!rows']=[{hpt:25}];
 const elements=XLSX.utils.aoa_to_sheet([['Commessa','Camion','Tipo unità','Codice pacco','Numero elemento','Master panel','Spessore (mm)','Lunghezza (mm)','Larghezza (mm)','Peso (kg)','Volume (m³)','Operatore scansione','Data scansione','Stato'],...model.elements.map(e=>[model.order,model.truck,e.unitType,e.packageCode,e.number,e.masterPanel,e.thickness,e.length,e.width,e.weight,e.volume,documentReference(e.scanOperator),excelDate(e.scannedAt),e.state])]);
 elements['!autofilter']={ref:`A1:N${end}`};elements['!cols']=[16,12,12,22,18,20,17,19,19,16,17,50,23,14].map(wch=>({wch}));elements['!rows']=[{hpt:28}];
 for(let row=2;row<=end;row++){for(const col of ['G','H','I'])elements[`${col}${row}`].z=Number.isInteger(elements[`${col}${row}`].v)?'#,##0':'#,##0.000';elements[`J${row}`].z='#,##0.0';elements[`K${row}`].z='#,##0.000';if(elements[`M${row}`])elements[`M${row}`].z='dd/mm/yyyy hh:mm';}
 XLSX.utils.sheet_add_aoa(elements,[['TOTALI']],{origin:`A${end+2}`});for(const [col,value,format] of [['J',model.totals.weight,'#,##0.0'],['K',model.totals.volume,'#,##0.000']] as const)elements[`${col}${end+2}`]={t:'n',v:value,f:`SUM(${col}2:${col}${end})`,z:format};
 XLSX.utils.book_append_sheet(workbook,summary,'Riepilogo');XLSX.utils.book_append_sheet(workbook,elements,'Elementi spediti');return workbook;
}
export function shipmentExcelBytes(model:PreparedShipmentDocument):ArrayBuffer{return XLSX.write(createShipmentWorkbook(model),{bookType:'xlsx',type:'array',compression:true}) as ArrayBuffer;}
