import type { LoadImport,LoadRecord,PanelRecord } from "../models/operational.js";
import type { LoadRepository } from "../repositories/loadRepository.js";
import { ApiError } from "../utils/apiError.js";

const normalizeTruck=(value:string)=>value.trim().toUpperCase().replace(/[\s-]+/g,"");
export class LoadService{
 constructor(private readonly repository:LoadRepository){}
 list():LoadRecord[]{return this.repository.list();}
 get(id:string):LoadRecord{const value=this.repository.find(id);if(!value)throw new ApiError(404,"RESOURCE_NOT_FOUND","Commessa non trovata");return value;}
 panels(id:string):PanelRecord[]{this.get(id);return this.repository.panels(id);}
 import(input:LoadImport):LoadRecord[]{const trucks=new Map<string,string>();for(const panel of input.pannelli){const normalized=normalizeTruck(panel.camion);if(normalized&&!trucks.has(normalized))trucks.set(normalized,panel.camion.trim());}if(!trucks.size)throw new ApiError(400,"VALIDATION_ERROR","La distinta non contiene camion validi");return this.repository.transaction(()=>{for(const truck of trucks.values()){const existing=this.repository.findByOrderTruck(input.commessa,truck);if(existing?.stato==="SPEDITO")throw new ApiError(409,"SHIPPED_LOAD","La commessa e il camion risultano già spediti");if(existing)throw new ApiError(409,"LOAD_ALREADY_EXISTS","Questa commessa e questo camion sono già presenti");}return[...trucks.values()].map(truck=>this.repository.createLoad(input,truck));});}
 updateImport(id:string,input:LoadImport):LoadRecord{const existing=this.get(id);if(existing.stato==="SPEDITO")throw new ApiError(409,"SHIPPED_LOAD","Una commessa spedita non può essere aggiornata");return this.repository.transaction(()=>{const updated=this.repository.updateImport(id,input);if(!updated)throw new ApiError(404,"RESOURCE_NOT_FOUND","Commessa non trovata");return updated;});}
 updateOrderImport(commessa:string,input:LoadImport):LoadRecord[]{if(commessa.trim().toUpperCase()!==input.commessa.trim().toUpperCase())throw new ApiError(400,"VALIDATION_ERROR","La commessa della richiesta non coincide con la distinta");const trucks=new Map<string,{name:string;panels:LoadImport["pannelli"]}>();for(const panel of input.pannelli){const key=normalizeTruck(panel.camion),entry=trucks.get(key);if(entry)entry.panels.push(panel);else trucks.set(key,{name:panel.camion.trim(),panels:[panel]});}return this.repository.transaction(()=>{const existing=this.repository.findByOrder(commessa);for(const load of existing){const incoming=trucks.get(normalizeTruck(load.camion));if(incoming){const updated=this.repository.updateImport(load.id,{...input,pannelli:incoming.panels});if(!updated)throw new ApiError(404,"RESOURCE_NOT_FOUND","Carico non trovato durante l'aggiornamento");trucks.delete(normalizeTruck(load.camion));continue;}if(!input.removeMissing)continue;const assessment=this.repository.assessLoadDeletion(load.id);if(assessment.blockingReason)throw new ApiError(409,"RESOURCE_IN_USE",`Il camion ${load.camion} non può essere rimosso. ${assessment.blockingReason}`);if(assessment.shipmentPlanIds.length||assessment.preventiveTransportAssignmentIds.length)throw new ApiError(409,"RESOURCE_IN_USE",`Il camion ${load.camion} ha una pianificazione o prenotazione collegata e non può essere rimosso dalla distinta.`);this.repository.deleteOrderRelations(assessment);}for(const entry of trucks.values())this.repository.createLoad({...input,pannelli:entry.panels},entry.name);return this.repository.findByOrder(commessa);});}
 delete(id:string,confirmPlanning:boolean):void{this.repository.transaction(()=>{const existing=this.get(id);const assessment=this.repository.assessLoadDeletion(existing.id);if(assessment.blockingReason)throw new ApiError(409,"RESOURCE_IN_USE",`Il carico ${existing.camion} della commessa ${existing.commessa} non può essere eliminato. ${assessment.blockingReason}`);if(assessment.shipmentPlanIds.length&&!confirmPlanning)throw new ApiError(409,"PREVENTIVE_PLAN_CONFIRMATION_REQUIRED",`Il carico ${existing.camion} della commessa ${existing.commessa} ha una pianificazione spedizione collegata. Eliminando il carico verrà eliminata anche la pianificazione. Vuoi continuare?`);this.repository.deleteOrderRelations(assessment);});}
 deleteOrder(commessa:string,confirmPlanning:boolean):void{this.repository.transaction(()=>{const assessment=this.repository.assessOrderDeletion(commessa);if(!assessment.loads.length)throw new ApiError(404,"RESOURCE_NOT_FOUND","Commessa non trovata");if(assessment.blockingReason)throw new ApiError(409,"RESOURCE_IN_USE",assessment.blockingReason);if(assessment.shipmentPlanIds.length&&!confirmPlanning)throw new ApiError(409,"PREVENTIVE_PLAN_CONFIRMATION_REQUIRED","La commessa ha una pianificazione spedizione collegata. Eliminando la commessa verrà eliminata anche la pianificazione. Vuoi continuare?");this.repository.deleteOrderRelations(assessment);});}
}
