import type { ScanningRepository } from "../repositories/scanningRepository.js";
import { ApiError } from "../utils/apiError.js";
export class ScanningService{
 constructor(private readonly repository:ScanningRepository){}
 warehouse(){return this.repository.warehouse();} listPackages(){return this.repository.listPackages();}
 getPackage(id:string){const value=this.repository.findPackage(id);if(!value)throw new ApiError(404,"RESOURCE_NOT_FOUND","Pacco non trovato");return value;}
 createPackage(input:{loadId:string;operatorId:string}){return this.repository.transaction(()=>{try{return this.repository.createPackage(input.loadId,input.operatorId);}catch{throw new ApiError(404,"RESOURCE_NOT_FOUND","Carico non trovato");}});}
 scan(id:string,input:{operatorId:string}){return this.repository.transaction(()=>{const panel=this.panel(id);if(panel.stato!=="MANCANTE")throw new ApiError(409,"PANEL_NOT_AVAILABLE","Elemento già registrato");return this.repository.scanPanel(id,input.operatorId);});}
 closeSingle(id:string,input:{operatorId:string}){return this.repository.transaction(()=>{const panel=this.panel(id);if(panel.stato!=="MANCANTE"||panel.packageId)throw new ApiError(409,"PANEL_NOT_AVAILABLE","Elemento non disponibile");return this.repository.closeSingle(id,input.operatorId);});}
 updateManualLocation(id:string,input:{location:string}){return this.repository.transaction(()=>{const panel=this.panel(id);if(panel.stato!=="DISPONIBILE")throw new ApiError(409,"PANEL_NOT_AVAILABLE","L'ubicazione è modificabile solo per gli elementi disponibili");const location=input.location.trim();return this.repository.updateManualLocation(id,location||null);});}
 updatePackageManualLocation(id:string,input:{location:string}){return this.repository.transaction(()=>{const pack=this.getPackage(id);if(pack.stato!=="DISPONIBILE")throw new ApiError(409,"PACKAGE_NOT_AVAILABLE","L'ubicazione è modificabile solo per i pacchi disponibili");const location=input.location.trim();return this.repository.updatePackageManualLocation(id,location||null);});}
 addPanel(packageId:string,input:{panelId:string;operatorId:string}){return this.repository.transaction(()=>{const pack=this.getPackage(packageId),panel=this.panel(input.panelId);if(pack.stato!=="APERTO")throw new ApiError(409,"PACKAGE_CLOSED","Il pacco è già chiuso");if(panel.loadId!==pack.loadId||panel.stato!=="MANCANTE"||panel.packageId)throw new ApiError(409,"PANEL_NOT_AVAILABLE","Elemento non disponibile");return this.repository.addPanel(packageId,input.panelId,input.operatorId);});}
 removePanel(packageId:string,panelId:string,input:{operatorId:string}){return this.repository.transaction(()=>{const pack=this.getPackage(packageId),panel=this.panel(panelId);if(pack.stato!=="APERTO"||panel.packageId!==packageId)throw new ApiError(409,"PANEL_NOT_IN_PACKAGE","Elemento non presente nel pacco aperto");return this.repository.removePanel(packageId,panelId,input.operatorId);});}
 closePackage(id:string,input:{codicePacco:string;operatoreId:string;lunghezzaPacco:number;larghezzaPacco:number;altezzaPacco:number}){return this.repository.transaction(()=>{const pack=this.getPackage(id);if(pack.stato!=="APERTO"||!pack.pannelli.length)throw new ApiError(409,"PACKAGE_NOT_CLOSABLE","Il pacco non può essere chiuso");if([input.lunghezzaPacco,input.larghezzaPacco,input.altezzaPacco].some(value=>!Number.isFinite(value)||value<=0))throw new ApiError(400,"VALIDATION_ERROR","Dimensioni non valide");return this.repository.closePackage(id,input.codicePacco,{length:input.lunghezzaPacco,width:input.larghezzaPacco,height:input.altezzaPacco},input.operatoreId);});}
 cancelPanel(id:string,input:{operatorId?:string}){return this.repository.transaction(()=>{const panel=this.panel(id);if(panel.stato==="CARICATO"||panel.stato==="SPEDITO")throw new ApiError(409,"RESOURCE_IN_USE","Elemento già utilizzato");this.repository.cancelSingle(id,input.operatorId??null);return{success:true};});}
 cancelPackage(id:string,input:{operatorId?:string}){return this.repository.transaction(()=>{const pack=this.getPackage(id);if(pack.stato==="CARICATO"||pack.stato==="SPEDITO")throw new ApiError(409,"RESOURCE_IN_USE","Pacco già caricato o spedito e non eliminabile");const usage=this.repository.packageLoadingUsage(id);if(usage.active>0)throw new ApiError(409,"RESOURCE_IN_USE","Il pacco è presente in una sessione di carico attiva. Rimuoverlo prima dal carico.");if(usage.historical>0)throw new ApiError(409,"RESOURCE_IN_USE","Il pacco è già stato movimentato in una sessione di carico e non può essere eliminato perché fa parte dello storico operativo.");if(!this.repository.cancelPackage(id,input.operatorId??null))throw new ApiError(500,"PACKAGE_DELETE_FAILED","Il pacco non è stato eliminato dal database");return{success:true};});}
 private panel(id:string){const value=this.repository.findPanel(id);if(!value)throw new ApiError(404,"RESOURCE_NOT_FOUND","Elemento non trovato");return value;}
}
