import PrintIcon from "@mui/icons-material/Print";
import { Box, Button, Paper, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { QRCodeSVG } from "qrcode.react";
import essepiLogo from "../../assets/essepi-logo-package-original.jpg";
import type { Pacco } from "../../models/Scanning";
import { formatPackageDimensions } from "../../utils/packageDimensions";
import { packageQrText } from "../../utils/panelQr";

const waitForLogo=(image:HTMLImageElement)=>image.complete&&image.naturalWidth>0?image.decode().catch(()=>undefined):new Promise<void>(resolve=>{image.addEventListener("load",()=>resolve(),{once:true});image.addEventListener("error",()=>resolve(),{once:true});});
export const printPackageDocument=async()=>{await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const logos=Array.from(document.querySelectorAll<HTMLImageElement>(".package-logo"));await Promise.all(logos.map(waitForLogo));window.print();};

export default function PackagePrintPreview({ pack }: { pack:Pacco }) {
  const qr=packageQrText(pack.codice,pack.commessa,pack.cliente,pack.camion,pack.numeroPezzi,pack.pesoTotale,pack.volumeTotale);
  const details=[["Commessa",pack.commessa],["Cliente",pack.cliente],["Camion",pack.camion],["Numero elementi",pack.numeroPezzi],["Dimensioni pacco",formatPackageDimensions(pack)],["Peso totale",`${pack.pesoTotale.toFixed(1)} kg`],["Volume totale",`${pack.volumeTotale.toFixed(3)} m³`],["Operatore",pack.operatore],["Data e ora",new Date(pack.chiusoIl).toLocaleString("it-IT")]];
  return <Paper className="package-print" sx={{mt:2,p:3}}>
    <style>{`@media print{@page{size:A4;margin:6mm 7mm 8mm}html,body{background:#fff!important}body *{visibility:hidden!important}.package-print,.package-print *{visibility:visible!important}.package-print{position:absolute!important;inset:0 auto auto 0!important;width:100%!important;color:#111!important;background:#fff!important;box-shadow:none!important;border:0!important;margin:0!important;padding:0!important}.package-print-collection{position:absolute!important;inset:0 auto auto 0!important;width:100%!important}.package-print-collection .package-print{position:relative!important;inset:auto!important;break-after:page;page-break-after:always}.package-print-collection .package-print:last-child{break-after:auto;page-break-after:auto}.no-print{display:none!important}.package-print td,.package-print th,.package-print h4,.package-print h6,.package-print p,.package-print span,.package-print b{color:#111!important}.package-label{break-inside:avoid;page-break-inside:avoid;-webkit-print-color-adjust:exact;print-color-adjust:exact}.package-logo{display:block!important;width:124px!important;height:124px!important;object-fit:contain!important;filter:none!important;opacity:1!important;mix-blend-mode:normal!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.package-qr{width:104px!important;height:104px!important}.package-table{width:100%!important;table-layout:fixed!important;break-inside:auto;page-break-inside:auto}.package-table thead{display:table-header-group}.package-table tr{break-inside:avoid;page-break-inside:avoid}.package-table th,.package-table td{padding:4px 8px!important}.package-table th:nth-child(6),.package-table td:nth-child(6),.package-table th:nth-child(7),.package-table td:nth-child(7){white-space:nowrap!important}.package-summary{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;column-gap:18px!important;white-space:nowrap!important}}`}</style>
    <Box className="no-print" sx={{display:"flex",justifyContent:"space-between",mb:2}}><Typography variant="h6">Anteprima pacco chiuso</Typography><Button variant="contained" startIcon={<PrintIcon/>} onClick={()=>void printPackageDocument()}>Ristampa etichetta e lista pacco</Button></Box>
    <Box className="package-label" sx={{border:1,borderColor:"divider",display:"grid",gridTemplateColumns:"minmax(0, 1fr) 112px",gap:2,p:2}}><Box><Box alt="Essepi - finestre & xlam" className="package-logo" component="img" src={essepiLogo} sx={{display:"block",height:124,mb:.5,objectFit:"contain",width:124}}/><Typography variant="overline" sx={{lineHeight:1.2}}>Etichetta pacco</Typography><Typography variant="h4" sx={{fontWeight:900,mb:1,lineHeight:1.1}}>{pack.codice}</Typography><Box sx={{display:"grid",gridTemplateColumns:"145px 1fr",columnGap:1,rowGap:.45}}>{details.map(([label,value])=><Box key={String(label)} sx={{display:"contents"}}><Typography color="text.secondary">{label}</Typography><Typography sx={{fontWeight:700}}>{value}</Typography></Box>)}</Box></Box><Box sx={{display:"flex",justifyContent:"center",pt:15}}><QRCodeSVG className="package-qr" value={qr} size={104} level="M" marginSize={1}/></Box></Box>
    <Typography variant="h6" sx={{mt:1.5,mb:.25}}>Elementi contenuti</Typography><Table className="package-table" size="small" sx={{tableLayout:"fixed",width:"100%"}}><colgroup><col style={{width:"16%"}}/><col style={{width:"20%"}}/><col style={{width:"12%"}}/><col style={{width:"13%"}}/><col style={{width:"13%"}}/><col style={{width:"13%"}}/><col style={{width:"13%"}}/></colgroup><TableHead><TableRow>{["Elemento","Master panel","Spessore","Lunghezza","Altezza","Peso","Volume"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{pack.pannelli.map(p=><TableRow key={p.numeroPannello}><TableCell>{p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)}</TableCell><TableCell>{Math.round(p.lunghezza)}</TableCell><TableCell>{Math.round(p.altezza)}</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{p.peso.toFixed(1)} kg</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{p.volume.toFixed(3)} m³</TableCell></TableRow>)}</TableBody></Table>
    <Box className="package-summary" sx={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",alignItems:"center",columnGap:2.25,mt:1.25,textAlign:"center",whiteSpace:"nowrap",width:"100%"}}><b>Dimensioni pacco: {formatPackageDimensions(pack)}</b><b>Totale pezzi: {pack.numeroPezzi}</b><b>Peso: {pack.pesoTotale.toFixed(1)} kg</b><b>Volume: {pack.volumeTotale.toFixed(3)} m³</b></Box>
  </Paper>;
}
