import PrintIcon from "@mui/icons-material/Print";
import { Box, Button, Paper, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { QRCodeSVG } from "qrcode.react";
import type { Pacco } from "../../models/Scanning";
import { packageQrText } from "../../utils/panelQr";
import { formatPackageDimensions } from "../../utils/packageDimensions";

export default function PackagePrintPreview({ pack }: { pack:Pacco }) {
  const qr=packageQrText(pack.codice,pack.commessa,pack.cliente,pack.camion,pack.numeroPezzi,pack.pesoTotale,pack.volumeTotale);
  return <Paper className="package-print" sx={{mt:2,p:3}}>
    <style>{`@media print{@page{size:A4;margin:12mm}html,body{background:#fff!important}body *{visibility:hidden!important}.package-print,.package-print *{visibility:visible!important}.package-print{position:absolute!important;inset:0 auto auto 0!important;width:100%!important;color:#111!important;background:#fff!important;box-shadow:none!important;border:0!important;margin:0!important;padding:0!important}.package-print-collection{position:absolute!important;inset:0 auto auto 0!important;width:100%!important}.package-print-collection .package-print{position:relative!important;inset:auto!important;break-after:page;page-break-after:always}.package-print-collection .package-print:last-child{break-after:auto;page-break-after:auto}.no-print{display:none!important}.package-print td,.package-print th,.package-print h4,.package-print h6,.package-print p,.package-print span,.package-print b{color:#111!important}.package-label{break-inside:avoid;page-break-inside:avoid}.package-table thead{display:table-header-group}.package-table tr{break-inside:avoid;page-break-inside:avoid}.package-table{break-inside:auto;page-break-inside:auto}}`}</style>
    <Box className="no-print" sx={{display:"flex",justifyContent:"space-between",mb:2}}><Typography variant="h6">Anteprima pacco chiuso</Typography><Button variant="contained" startIcon={<PrintIcon/>} onClick={()=>window.print()}>Ristampa etichetta e lista pacco</Button></Box>
    <Box className="package-label" sx={{border:1,borderColor:"divider",display:"grid",gridTemplateColumns:"1fr auto",gap:3,p:3}}><Box><Typography variant="overline">Etichetta pacco</Typography><Typography variant="h4" sx={{fontWeight:900,mb:2}}>{pack.codice}</Typography><Box sx={{display:"grid",gridTemplateColumns:"150px 1fr",gap:1}}>{[["Commessa",pack.commessa],["Cliente",pack.cliente],["Camion",pack.camion],["Numero pannelli",pack.numeroPezzi],["Dimensioni pacco",formatPackageDimensions(pack)],["Peso totale",`${pack.pesoTotale.toFixed(1)} kg`],["Volume totale",`${pack.volumeTotale.toFixed(3)} m³`],["Operatore",pack.operatore],["Data e ora",new Date(pack.chiusoIl).toLocaleString("it-IT")]].map(([label,value])=><Box key={String(label)} sx={{display:"contents"}}><Typography color="text.secondary">{label}</Typography><Typography sx={{fontWeight:700}}>{value}</Typography></Box>)}</Box></Box><QRCodeSVG value={qr} size={190} level="M" marginSize={1}/></Box>
    <Typography variant="h6" sx={{mt:3}}>Pannelli contenuti</Typography><Table className="package-table" size="small"><TableHead><TableRow>{["Pannello","Master panel","Spessore","Lunghezza","Altezza","Peso","Volume"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{pack.pannelli.map(p=><TableRow key={p.numeroPannello}><TableCell>{p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)}</TableCell><TableCell>{Math.round(p.lunghezza)}</TableCell><TableCell>{Math.round(p.altezza)}</TableCell><TableCell>{p.peso.toFixed(1)} kg</TableCell><TableCell>{p.volume.toFixed(3)} m³</TableCell></TableRow>)}</TableBody></Table>
    <Box sx={{display:"flex",justifyContent:"flex-end",gap:4,mt:2}}><b>Dimensioni pacco: {formatPackageDimensions(pack)}</b><b>Totale pezzi: {pack.numeroPezzi}</b><b>Peso: {pack.pesoTotale.toFixed(1)} kg</b><b>Volume: {pack.volumeTotale.toFixed(3)} m³</b></Box>
  </Paper>;
}
