import PrintIcon from "@mui/icons-material/Print";
import { Box, Button, Paper, Table, TableBody, TableCell, TableHead, TableRow, Typography } from "@mui/material";
import { QRCodeSVG } from "qrcode.react";
import essepiLogo from "../../assets/essepi-logo-package-original.jpg";
import type { Pacco } from "../../models/Scanning";
import { formatPackageDimensions } from "../../utils/packageDimensions";
import { packageQrText } from "../../utils/panelQr";
import { isDemoEnvironment } from "../../services/demoBranding";

const waitForLogo=(image:HTMLImageElement)=>image.complete&&image.naturalWidth>0?image.decode().catch(()=>undefined):new Promise<void>(resolve=>{image.addEventListener("load",()=>resolve(),{once:true});image.addEventListener("error",()=>resolve(),{once:true});});
export const printPackageDocument=async()=>{await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const logos=Array.from(document.querySelectorAll<HTMLImageElement>(".package-logo"));await Promise.all(logos.map(waitForLogo));window.print();};

export default function PackagePrintPreview({ pack }: { pack:Pacco }) {
  const qr=packageQrText(pack.codice,pack.commessa,pack.cliente,pack.camion,pack.numeroPezzi,pack.pesoTotale,pack.volumeTotale);
  const details=[["Commessa",pack.commessa],["Cliente",pack.cliente],["Camion",pack.camion],["Numero elementi",pack.numeroPezzi],["Dimensioni pacco",formatPackageDimensions(pack)],["Peso totale",`${pack.pesoTotale.toFixed(1)} kg`],["Volume totale",`${pack.volumeTotale.toFixed(3)} m³`],["Operatore",pack.operatore],["Data e ora",new Date(pack.chiusoIl).toLocaleString("it-IT")]];
  const detailColumns=[[0,1,2,7],[3,5,6,8,4]].map(indices=>indices.map(index=>details[index]!));
  return <Paper className="package-print" sx={{mt:2,p:3}}>
    <style>{`@media print{@page{size:A4;margin:6mm 7mm 8mm}html:has(.package-print),body:has(.package-print){background:#fff!important;margin:0!important;padding:0!important;width:196mm!important;max-width:100%!important;min-width:0!important;height:auto!important;min-height:0!important;overflow:visible!important}body:has(.package-print) *:has(.package-print):not(.package-print-collection){display:contents!important}body:has(.package-print) *:not(.package-print):not(.package-print *):not(:has(.package-print)){display:none!important}.package-print,.package-print *{box-sizing:border-box!important}.package-print{position:static!important;inset:auto!important;width:100%!important;max-width:100%!important;min-width:0!important;transform:none!important;color:#111!important;background:#fff!important;box-shadow:none!important;border:0!important;margin:0!important;padding:0!important}.package-print-collection{position:static!important;inset:auto!important;width:100%!important;max-width:100%!important;box-sizing:border-box!important}.package-label,.package-heading,.package-details,.package-table-wrap,.package-table{max-width:100%!important;min-width:0!important}.package-print-collection .package-print{position:relative!important;inset:auto!important;break-after:page;page-break-after:always}.package-print-collection .package-print:last-child{break-after:auto;page-break-after:auto}.no-print{display:none!important}.package-print td,.package-print th,.package-print h4,.package-print h6,.package-print p,.package-print span,.package-print b{color:#111!important}.package-label{break-inside:avoid;page-break-inside:avoid;-webkit-print-color-adjust:exact;print-color-adjust:exact}.package-logo{display:block!important;width:124px!important;height:124px!important;object-fit:contain!important;filter:none!important;opacity:1!important;mix-blend-mode:normal!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.package-qr{width:104px!important;height:104px!important}.package-heading{grid-template-columns:124px minmax(0,1fr) 128px!important}.package-identity{grid-row:1!important;grid-column:2!important}.package-qr-frame{grid-column:3!important}.package-details{grid-template-columns:repeat(2,minmax(0,1fr))!important}.package-print h6{break-after:avoid;page-break-after:avoid}.package-table-wrap{overflow:visible!important}.package-table{min-width:0!important;width:100%!important;table-layout:fixed!important;break-inside:auto;page-break-inside:auto}.package-table thead{display:table-header-group}.package-table tr{break-inside:avoid;page-break-inside:avoid}.package-table th,.package-table td{padding:2px 6px!important}.package-table th:nth-child(6),.package-table td:nth-child(6),.package-table th:nth-child(7),.package-table td:nth-child(7){white-space:nowrap!important}}`}</style>
    <Box className="no-print" sx={{display:"flex",justifyContent:"space-between",mb:2}}><Typography variant="h6">Anteprima pacco chiuso</Typography><Button variant="contained" startIcon={<PrintIcon/>} onClick={()=>void printPackageDocument()}>Ristampa etichetta e lista pacco</Button></Box>
    <Box className="package-label" sx={{border:1,borderColor:"divider",p:1.5}}>
      <Box sx={{display:"grid",gridTemplateColumns:{xs:"124px minmax(0,1fr)",sm:"124px minmax(0,1fr) 128px"},alignItems:"start",gap:1.5}} className="package-heading">
        {isDemoEnvironment?<Box sx={{alignItems:"center",bgcolor:"primary.main",color:"primary.contrastText",display:"flex",fontSize:".75rem",fontWeight:900,height:44,justifyContent:"center",width:100}}>SisLog DEMO</Box>:<Box alt="Essepi - finestre & xlam" className="package-logo" component="img" src={essepiLogo} sx={{display:"block",height:124,objectFit:"contain",width:124}}/>}
        <Box className="package-identity" sx={{minWidth:0,textAlign:"center",gridRow:{xs:2,sm:1},gridColumn:{xs:"1 / -1",sm:2},pt:.5}}><Typography variant="overline" sx={{lineHeight:1.2}}>Etichetta pacco</Typography><Typography variant="h4" sx={{fontWeight:900,lineHeight:1.1,fontSize:"24pt",overflowWrap:"anywhere"}}>{pack.codice}</Typography></Box>
        <Box className="package-qr-frame" sx={{justifySelf:"end",p:"12px",bgcolor:"#fff",lineHeight:0,gridColumn:{xs:2,sm:3},gridRow:1}}><QRCodeSVG className="package-qr" value={qr} size={104} level="M" marginSize={1}/></Box>
      </Box>
      <Box className="package-details" sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(2,minmax(0,1fr))"},columnGap:3,rowGap:1,mt:1}}>
        {detailColumns.map((column,i)=><Box key={i} sx={{display:"grid",gridTemplateColumns:"120px minmax(0,1fr)",columnGap:1,rowGap:.4,alignContent:"start"}}>{column.map(([label,value])=><Box key={String(label)} sx={{display:"contents"}}><Typography sx={{fontSize:"11pt",lineHeight:1.25,color:"text.secondary"}}>{label}</Typography><Typography sx={{fontSize:"11pt",lineHeight:1.25,fontWeight:700,overflowWrap:"anywhere",minWidth:0}}>{value}</Typography></Box>)}</Box>)}
      </Box>
    </Box>
    <Typography variant="h6" sx={{mt:.75,mb:.125}}>Elementi contenuti</Typography><Box className="package-table-wrap" sx={{overflowX:"auto"}}><Table className="package-table" size="small" sx={{tableLayout:"fixed",width:"100%",minWidth:700,"& th":{fontSize:"12pt",fontWeight:700},"& td":{fontSize:"12pt"},"& th, & td":{px:.75,py:.25,lineHeight:1.2,overflowWrap:"anywhere"}}}><colgroup><col style={{width:"14%"}}/><col style={{width:"9%"}}/><col style={{width:"14%"}}/><col style={{width:"16%"}}/><col style={{width:"14%"}}/><col style={{width:"16%"}}/><col style={{width:"17%"}}/></colgroup><TableHead><TableRow>{["Elemento","MP","Spessore","Lunghezza","Altezza","Peso","Volume"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{pack.pannelli.map(p=><TableRow key={p.numeroPannello}><TableCell>{p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)}</TableCell><TableCell>{Math.round(p.lunghezza)}</TableCell><TableCell>{Math.round(p.altezza)}</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{p.peso.toFixed(1)} kg</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{p.volume.toFixed(3)} m³</TableCell></TableRow>)}</TableBody></Table></Box>
  </Paper>;
}
