import type{DatabaseSync}from"node:sqlite";
import type{DestinationType,LoadingSessionRecord,LoadingStatus,LoadingUnitRecord}from"../models/operational.js";
import type{TransportRepository}from"./transportRepository.js";
const str=(r:Record<string,unknown>,k:string)=>String(r[k]??"");const nullable=(r:Record<string,unknown>,k:string)=>typeof r[k]==="string"?r[k] as string:null;
export class LoadingRepository{
 constructor(private readonly db:DatabaseSync,private readonly transports?:TransportRepository){}
 unitInfo(type:"PANEL"|"PACKAGE",id:string):{loadId:string;stato:string;packageId:string|null}|null{const row=type==="PANEL"?this.db.prepare("SELECT loadId,stato,packageId FROM Panels WHERE id=?").get(id):this.db.prepare("SELECT loadId,stato,NULL packageId FROM Packages WHERE id=?").get(id);if(!row)return null;const r=row as Record<string,unknown>;return{loadId:str(r,"loadId"),stato:str(r,"stato"),packageId:nullable(r,"packageId")};}
 transaction<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const value=fn();this.db.exec("COMMIT");return value;}catch(e){this.db.exec("ROLLBACK");throw e;}}
 isComplete(sessionId:string,loadId:string):boolean{const expected=this.db.prepare("SELECT (SELECT COUNT(*) FROM Panels WHERE loadId=? AND packageId IS NULL AND stato IN('DISPONIBILE','CARICATO'))+(SELECT COUNT(*) FROM Packages WHERE loadId=? AND stato IN('DISPONIBILE','CARICATO')) total").get(loadId,loadId) as {total:number};const loaded=this.db.prepare("SELECT COUNT(*) total FROM LoadingUnits WHERE loadingSessionId=? AND active=1").get(sessionId) as {total:number};return expected.total>0&&expected.total===loaded.total;}
 list():LoadingSessionRecord[]{return this.db.prepare("SELECT s.*,l.commessa,l.cliente,l.camion FROM LoadingSessions s JOIN Loads l ON l.id=s.loadId ORDER BY s.startedAt DESC").all().map(r=>this.mapSession(r));}
 find(id:string):LoadingSessionRecord|null{const row=this.db.prepare("SELECT s.*,l.commessa,l.cliente,l.camion FROM LoadingSessions s JOIN Loads l ON l.id=s.loadId WHERE s.id=?").get(id);return row?this.mapSession(row):null;}
 findByLoad(loadId:string):LoadingSessionRecord|null{const row=this.db.prepare("SELECT s.*,l.commessa,l.cliente,l.camion FROM LoadingSessions s JOIN Loads l ON l.id=s.loadId WHERE s.loadId=?").get(loadId);return row?this.mapSession(row):null;}
 create(loadId:string,input:{operatorId:string;destinationType:DestinationType;trailerId?:string;carrierId?:string}):LoadingSessionRecord{const id=crypto.randomUUID(),now=new Date().toISOString();this.db.prepare("INSERT INTO LoadingSessions(id,loadId,stato,operatorId,destinationType,trailerId,carrierId,startedAt,createdAt,updatedAt) VALUES(?,?,'DA_CARICARE',?,?,?,?,?,?,?)").run(id,loadId,input.operatorId,input.destinationType,input.trailerId??null,input.carrierId??null,now,now,now);if(input.destinationType==="RIMORCHIO_ESSEPI"&&input.trailerId)this.transports?.assign(input.trailerId,loadId,id);this.event(loadId,id,"LOADING_STARTED",input.operatorId,now,null);return this.find(id)!;}
 update(id:string,input:{operatorId:string;destinationType:DestinationType;trailerId?:string;carrierId?:string}):LoadingSessionRecord{const current=this.find(id)!,now=new Date().toISOString();this.db.prepare("UPDATE LoadingSessions SET operatorId=?,destinationType=?,trailerId=?,carrierId=?,updatedAt=? WHERE id=?").run(input.operatorId,input.destinationType,input.trailerId??null,input.carrierId??null,now,id);if(input.destinationType==="RIMORCHIO_ESSEPI"&&input.trailerId)this.transports?.assign(input.trailerId,current.loadId,id);else this.transports?.releaseByLoad(current.loadId,now);return this.find(id)!;}
 addUnit(sessionId:string,input:{unitType:"PANEL"|"PACKAGE";panelId?:string;packageId?:string;operatorId:string}):LoadingSessionRecord{const id=crypto.randomUUID(),now=new Date().toISOString(),panelId=input.panelId??null,packageId=input.packageId??null;this.db.prepare("INSERT INTO LoadingUnits(id,loadingSessionId,unitType,panelId,packageId,loadedAt,loadedByOperatorId,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)").run(id,sessionId,input.unitType,panelId,packageId,now,input.operatorId,now,now);if(input.unitType==="PANEL")this.db.prepare("UPDATE Panels SET stato='CARICATO',updatedAt=? WHERE id=?").run(now,panelId);else{this.db.prepare("UPDATE Packages SET stato='CARICATO',updatedAt=? WHERE id=?").run(now,packageId);this.db.prepare("UPDATE Panels SET stato='CARICATO',updatedAt=? WHERE packageId=?").run(now,packageId);}this.db.prepare("UPDATE LoadingSessions SET stato='IN_CARICO',updatedAt=? WHERE id=?").run(now,sessionId);const s=this.find(sessionId)!;this.db.prepare("UPDATE Loads SET stato='IN_CARICO',updatedAt=? WHERE id=?").run(now,s.loadId);this.event(s.loadId,sessionId,"UNIT_LOADED",input.operatorId,now,input.unitType);return this.find(sessionId)!;}
 removeUnit(sessionId:string,unitId:string,operatorId:string):LoadingSessionRecord{const unit=this.db.prepare("SELECT * FROM LoadingUnits WHERE id=? AND loadingSessionId=? AND active=1").get(unitId,sessionId) as Record<string,unknown>,now=new Date().toISOString(),panelId=nullable(unit,"panelId"),packageId=nullable(unit,"packageId");this.db.prepare("UPDATE LoadingUnits SET active=0,removedAt=?,removedByOperatorId=?,updatedAt=? WHERE id=?").run(now,operatorId,now,unitId);if(str(unit,"unitType")==="PANEL")this.db.prepare("UPDATE Panels SET stato='DISPONIBILE',updatedAt=? WHERE id=?").run(now,panelId);else{this.db.prepare("UPDATE Packages SET stato='DISPONIBILE',updatedAt=? WHERE id=?").run(now,packageId);this.db.prepare("UPDATE Panels SET stato='DISPONIBILE',updatedAt=? WHERE packageId=?").run(now,packageId);}const s=this.find(sessionId)!;this.event(s.loadId,sessionId,"UNIT_UNLOADED",operatorId,now,null);return s;}
 complete(id:string):LoadingSessionRecord{const s=this.find(id)!,now=new Date().toISOString();this.db.prepare("UPDATE LoadingSessions SET stato='ATTESA_SPEDIZIONE',completedAt=?,updatedAt=? WHERE id=?").run(now,now,id);this.db.prepare("UPDATE Loads SET stato='ATTESA_SPEDIZIONE',updatedAt=? WHERE id=?").run(now,s.loadId);this.transports?.markLoadedBySession(id,now);this.event(s.loadId,id,"LOADING_COMPLETED",s.operatorId,now,null);return this.find(id)!;}
 reopen(id:string,note?:string):LoadingSessionRecord{const s=this.find(id)!,now=new Date().toISOString();this.db.prepare("UPDATE LoadingSessions SET stato='IN_CARICO',reopenedAt=?,updatedAt=? WHERE id=?").run(now,now,id);this.db.prepare("UPDATE Loads SET stato='IN_CARICO',updatedAt=? WHERE id=?").run(now,s.loadId);this.transports?.markLoadingBySession(id,now);this.event(s.loadId,id,"LOADING_REOPENED",s.operatorId,now,note??null);return this.find(id)!;}
 ship(id:string,carrierId?:string):LoadingSessionRecord{const s=this.find(id)!,now=new Date().toISOString(),resolvedCarrierId=carrierId??s.carrierId;this.db.prepare("UPDATE LoadingSessions SET stato='SPEDITO',carrierId=?,shippedAt=?,updatedAt=? WHERE id=?").run(resolvedCarrierId,now,now,id);this.db.prepare("UPDATE Loads SET stato='SPEDITO',updatedAt=? WHERE id=?").run(now,s.loadId);this.db.prepare("UPDATE ShipmentPlans SET actualDepartureDate=COALESCE(actualDepartureDate,?),carrierId=COALESCE(?,carrierId),updatedAt=? WHERE loadId=?").run(now,resolvedCarrierId,now,s.loadId);if(s.trailerId)this.transports?.departBySession(id,now);this.db.prepare("UPDATE Panels SET stato='SPEDITO',updatedAt=? WHERE id IN(SELECT panelId FROM LoadingUnits WHERE loadingSessionId=? AND active=1 AND panelId IS NOT NULL) OR packageId IN(SELECT packageId FROM LoadingUnits WHERE loadingSessionId=? AND active=1 AND packageId IS NOT NULL)").run(now,id,id);this.db.prepare("UPDATE Packages SET stato='SPEDITO',updatedAt=? WHERE id IN(SELECT packageId FROM LoadingUnits WHERE loadingSessionId=? AND active=1)").run(now,id);this.event(s.loadId,id,"PARTENZA_CONFERMATA",null,now,null);return this.find(id)!;}
 private units(id:string):LoadingUnitRecord[]{return this.db.prepare("SELECT u.*,COALESCE(p.numeroPannello,k.codicePacco) code,COALESCE(p.peso,k.pesoTotale) weight,COALESCE(p.volume,k.volumeTotale) volume FROM LoadingUnits u LEFT JOIN Panels p ON p.id=u.panelId LEFT JOIN Packages k ON k.id=u.packageId WHERE u.loadingSessionId=? AND u.active=1 ORDER BY u.loadedAt").all(id).map(v=>{const r=v as Record<string,unknown>;return{id:str(r,"id"),loadingSessionId:id,unitType:str(r,"unitType") as "PANEL"|"PACKAGE",panelId:nullable(r,"panelId"),packageId:nullable(r,"packageId"),code:str(r,"code"),weight:Number(r.weight),volume:Number(r.volume),loadedAt:str(r,"loadedAt"),loadedByOperatorId:str(r,"loadedByOperatorId"),active:Boolean(r.active)};});}
 private mapSession(v:unknown):LoadingSessionRecord{const r=v as Record<string,unknown>,id=str(r,"id");const events=this.db.prepare("SELECT type,operatorId,timestamp,note FROM OperationalEvents WHERE loadingSessionId=? ORDER BY timestamp").all(id).map(value=>{const event=value as Record<string,unknown>;return{type:str(event,"type"),operatorId:nullable(event,"operatorId"),timestamp:str(event,"timestamp"),note:nullable(event,"note")};});return{id,loadId:str(r,"loadId"),commessa:str(r,"commessa"),cliente:str(r,"cliente"),camion:str(r,"camion"),stato:str(r,"stato") as LoadingStatus,operatorId:str(r,"operatorId"),destinationType:str(r,"destinationType") as DestinationType,trailerId:nullable(r,"trailerId"),carrierId:nullable(r,"carrierId"),startedAt:str(r,"startedAt"),completedAt:nullable(r,"completedAt"),reopenedAt:nullable(r,"reopenedAt"),shippedAt:nullable(r,"shippedAt"),createdAt:str(r,"createdAt"),updatedAt:str(r,"updatedAt"),units:this.units(id),events};}
 private event(loadId:string,sessionId:string,type:string,operatorId:string|null,time:string,note:string|null){this.db.prepare("INSERT INTO OperationalEvents(id,loadId,loadingSessionId,type,operatorId,timestamp,note)VALUES(?,?,?,?,?,?,?)").run(crypto.randomUUID(),loadId,sessionId,type,operatorId,time,note);}
}
