import type { DatabaseSync } from "node:sqlite";
import type { LoadImport,LoadRecord,LoadStatus,PanelImport,PanelRecord,PanelStatus } from "../models/operational.js";
import { requiredNumber,requiredString } from "./repositoryUtils.js";

const panelFromRow=(value:unknown):PanelRecord=>{const row=value as Record<string,unknown>;return{id:requiredString(row,"id"),loadId:requiredString(row,"loadId"),numeroPannello:requiredString(row,"numeroPannello"),numeroCliente:requiredString(row,"numeroCliente"),numeroMasterPanel:requiredString(row,"numeroMasterPanel"),camion:requiredString(row,"camion"),lato1:requiredString(row,"lato1"),lato2:requiredString(row,"lato2"),tipoPannello:requiredString(row,"tipoPannello"),quantita:requiredNumber(row,"quantita"),spessore:requiredNumber(row,"spessore"),lunghezza:requiredNumber(row,"lunghezza"),altezza:requiredNumber(row,"altezza"),superficie:requiredNumber(row,"superficie"),volume:requiredNumber(row,"volume"),peso:requiredNumber(row,"peso"),stato:requiredString(row,"stato") as PanelStatus,createdAt:requiredString(row,"createdAt"),updatedAt:requiredString(row,"updatedAt")};};
const loadBase=(value:unknown):Omit<LoadRecord,"pannelli">=>{const row=value as Record<string,unknown>;return{id:requiredString(row,"id"),commessa:requiredString(row,"commessa"),cliente:requiredString(row,"cliente"),numeroCliente:requiredString(row,"numeroCliente"),riferimentoOrdine:requiredString(row,"riferimentoOrdine"),camion:requiredString(row,"camion"),stato:requiredString(row,"stato") as LoadStatus,createdAt:requiredString(row,"createdAt"),updatedAt:requiredString(row,"updatedAt")};};
const normalizedTruck=(value:string)=>value.trim().toUpperCase().replace(/[\s-]+/g,"");
export class LoadRepository{
 constructor(private readonly database:DatabaseSync){}
 list():LoadRecord[]{return this.database.prepare("SELECT * FROM Loads ORDER BY commessa,camion").all().map(row=>this.withPanels(loadBase(row)));}
 find(id:string):LoadRecord|null{const row=this.database.prepare("SELECT * FROM Loads WHERE id=?").get(id);return row?this.withPanels(loadBase(row)):null;}
 findByOrderTruck(commessa:string,camion:string):LoadRecord|null{const row=this.database.prepare("SELECT * FROM Loads WHERE UPPER(TRIM(commessa))=UPPER(TRIM(?)) AND UPPER(REPLACE(REPLACE(TRIM(camion),' ',''),'-',''))=UPPER(REPLACE(REPLACE(TRIM(?),' ',''),'-','')) ORDER BY CASE WHEN stato='SPEDITO' THEN 0 ELSE 1 END LIMIT 1").get(commessa,camion);return row?this.withPanels(loadBase(row)):null;}
 panels(id:string):PanelRecord[]{return this.database.prepare("SELECT * FROM Panels WHERE loadId=? ORDER BY numeroPannello").all(id).map(panelFromRow);}
 transaction<T>(operation:()=>T):T{this.database.exec("BEGIN IMMEDIATE");try{const result=operation();this.database.exec("COMMIT");return result;}catch(error:unknown){this.database.exec("ROLLBACK");throw error;}}
 createLoad(input:LoadImport,camion:string):LoadRecord{const id=crypto.randomUUID();const now=new Date().toISOString();this.database.prepare("INSERT INTO Loads (id,commessa,cliente,numeroCliente,riferimentoOrdine,camion,stato,createdAt,updatedAt) VALUES (?,?,?,?,?,?,'DA_COMPLETARE',?,?)").run(id,input.commessa.trim(),input.cliente,input.numeroCliente,input.riferimentoOrdine,camion.trim(),now,now);for(const panel of input.pannelli.filter(item=>normalizedTruck(item.camion)===normalizedTruck(camion)))this.insertPanel(id,panel,now);return this.find(id)!;}
 updateImport(id:string,input:LoadImport):LoadRecord|null{const existing=this.find(id);if(!existing)return null;const now=new Date().toISOString();this.database.prepare("UPDATE Loads SET cliente=?,numeroCliente=?,riferimentoOrdine=?,updatedAt=? WHERE id=?").run(input.cliente,input.numeroCliente,input.riferimentoOrdine,now,id);const incoming=new Map(input.pannelli.filter(item=>normalizedTruck(item.camion)===normalizedTruck(existing.camion)).map(item=>[item.numeroPannello.trim(),item]));for(const panel of existing.pannelli){const next=incoming.get(panel.numeroPannello.trim());if(next){this.database.prepare("UPDATE Panels SET numeroCliente=?,numeroMasterPanel=?,camion=?,lato1=?,lato2=?,tipoPannello=?,quantita=?,spessore=?,lunghezza=?,altezza=?,superficie=?,volume=?,peso=?,updatedAt=? WHERE id=?").run(next.numeroCliente,next.numeroMasterPanel,next.camion.trim(),next.lato1,next.lato2,next.tipoPannello,next.quantita,next.spessore,next.lunghezza,next.altezza,next.superficie,next.volume,next.peso,now,panel.id);incoming.delete(panel.numeroPannello.trim());}else if(input.removeMissing)this.database.prepare("DELETE FROM Panels WHERE id=?").run(panel.id);}
 for(const panel of incoming.values())this.insertPanel(id,panel,now);return this.find(id);}
 delete(id:string):boolean{return this.database.prepare("DELETE FROM Loads WHERE id=?").run(id).changes>0;}
 private withPanels(load:Omit<LoadRecord,"pannelli">):LoadRecord{return{...load,pannelli:this.panels(load.id)};}
 private insertPanel(loadId:string,panel:PanelImport,now:string):void{this.database.prepare("INSERT OR IGNORE INTO Panels (id,loadId,numeroPannello,numeroCliente,numeroMasterPanel,camion,lato1,lato2,tipoPannello,quantita,spessore,lunghezza,altezza,superficie,volume,peso,stato,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'DA_COMPLETARE',?,?)").run(crypto.randomUUID(),loadId,panel.numeroPannello.trim(),panel.numeroCliente,panel.numeroMasterPanel,panel.camion.trim(),panel.lato1,panel.lato2,panel.tipoPannello,panel.quantita,panel.spessore,panel.lunghezza,panel.altezza,panel.superficie,panel.volume,panel.peso,now,now);}
}
