import type { DatabaseSync } from "node:sqlite";
import type { PackageRecord,PackageStatus,PanelRecord,PanelStatus,WarehouseRecord } from "../models/operational.js";
import { requiredNumber,requiredString } from "./repositoryUtils.js";

const nullableString=(row:Record<string,unknown>,key:string)=>typeof row[key]==="string"?row[key] as string:null;
const nullableNumber=(row:Record<string,unknown>,key:string)=>typeof row[key]==="number"?row[key] as number:null;
const panel=(value:unknown):PanelRecord=>{const row=value as Record<string,unknown>;return{id:requiredString(row,"id"),loadId:requiredString(row,"loadId"),numeroPannello:requiredString(row,"numeroPannello"),numeroCliente:requiredString(row,"numeroCliente"),numeroMasterPanel:requiredString(row,"numeroMasterPanel"),camion:requiredString(row,"camion"),lato1:requiredString(row,"lato1"),lato2:requiredString(row,"lato2"),tipoPannello:requiredString(row,"tipoPannello"),quantita:requiredNumber(row,"quantita"),spessore:requiredNumber(row,"spessore"),lunghezza:requiredNumber(row,"lunghezza"),altezza:requiredNumber(row,"altezza"),superficie:requiredNumber(row,"superficie"),volume:requiredNumber(row,"volume"),peso:requiredNumber(row,"peso"),stato:requiredString(row,"stato") as PanelStatus,packageId:nullableString(row,"packageId"),scannedAt:nullableString(row,"scannedAt"),scannedByOperatorId:nullableString(row,"scannedByOperatorId"),createdAt:requiredString(row,"createdAt"),updatedAt:requiredString(row,"updatedAt")};};
const packageBase=(value:unknown):Omit<PackageRecord,"pannelli">=>{const row=value as Record<string,unknown>;return{id:requiredString(row,"id"),codicePacco:requiredString(row,"codicePacco"),loadId:requiredString(row,"loadId"),commessa:requiredString(row,"commessa"),cliente:requiredString(row,"cliente"),camion:requiredString(row,"camion"),stato:requiredString(row,"stato") as PackageStatus,numeroPannelli:requiredNumber(row,"numeroPannelli"),pesoTotale:requiredNumber(row,"pesoTotale"),volumeTotale:requiredNumber(row,"volumeTotale"),lunghezzaPacco:nullableNumber(row,"lunghezzaPacco"),larghezzaPacco:nullableNumber(row,"larghezzaPacco"),altezzaPacco:nullableNumber(row,"altezzaPacco"),operatoreId:requiredString(row,"operatoreId"),openedAt:requiredString(row,"openedAt"),closedAt:nullableString(row,"closedAt"),createdAt:requiredString(row,"createdAt"),updatedAt:requiredString(row,"updatedAt")};};

export class ScanningRepository{
 constructor(private readonly database:DatabaseSync){}
 transaction<T>(fn:()=>T):T{this.database.exec("BEGIN IMMEDIATE");try{const result=fn();this.database.exec("COMMIT");return result;}catch(error:unknown){this.database.exec("ROLLBACK");throw error;}}
 findPanel(id:string):PanelRecord|null{const row=this.database.prepare("SELECT * FROM Panels WHERE id=?").get(id);return row?panel(row):null;}
 findPackage(id:string):PackageRecord|null{const row=this.database.prepare("SELECT * FROM Packages WHERE id=?").get(id);return row?this.withPanels(packageBase(row)):null;}
 listPackages():PackageRecord[]{return this.database.prepare("SELECT * FROM Packages ORDER BY createdAt DESC").all().map(row=>this.withPanels(packageBase(row)));}
 warehouse():WarehouseRecord{const singles=this.database.prepare("SELECT Panels.*,Loads.commessa AS commessa FROM Panels JOIN Loads ON Loads.id=Panels.loadId WHERE Panels.stato IN ('DISPONIBILE','CARICATO','SPEDITO') AND Panels.packageId IS NULL ORDER BY Panels.scannedAt DESC").all().map(value=>Object.assign(panel(value),{commessa:String((value as Record<string,unknown>).commessa)}));const packages=this.listPackages();return{singles,packages:packages.filter(item=>item.stato!=="APERTO"),openPackages:packages.filter(item=>item.stato==="APERTO")};}
 createPackage(loadId:string,operatorId:string):PackageRecord{const load=this.database.prepare("SELECT * FROM Loads WHERE id=?").get(loadId) as Record<string,unknown>|undefined;if(!load)throw new Error("LOAD_NOT_FOUND");const id=crypto.randomUUID(),now=new Date().toISOString();const code=`DRAFT-${id}`;this.database.prepare("INSERT INTO Packages(id,codicePacco,loadId,commessa,cliente,camion,stato,operatoreId,openedAt,createdAt,updatedAt) VALUES(?,?,?,?,?,?,'APERTO',?,?,?,?)").run(id,code,loadId,String(load.commessa),String(load.cliente),String(load.camion),operatorId,now,now,now);this.event(loadId,null,id,"PACKAGE_OPENED",operatorId,now);return this.findPackage(id)!;}
 scanPanel(id:string,operatorId:string):PanelRecord{const current=this.findPanel(id)!;const now=new Date().toISOString();this.database.prepare("UPDATE Panels SET scannedAt=?,scannedByOperatorId=?,updatedAt=? WHERE id=?").run(now,operatorId,now,id);this.event(current.loadId,id,current.packageId,"PANEL_SCANNED",operatorId,now);return this.findPanel(id)!;}
 closeSingle(id:string,operatorId:string):PanelRecord{const current=this.findPanel(id)!;const now=new Date().toISOString();this.database.prepare("UPDATE Panels SET stato='DISPONIBILE',packageId=NULL,scannedAt=?,scannedByOperatorId=?,updatedAt=? WHERE id=?").run(now,operatorId,now,id);this.event(current.loadId,id,null,"SINGLE_CLOSED",operatorId,now);return this.findPanel(id)!;}
 addPanel(packageId:string,panelId:string,operatorId:string):PackageRecord{const pack=this.findPackage(packageId)!,now=new Date().toISOString();this.database.prepare("UPDATE Panels SET stato='IN_LAVORAZIONE_PACCO',packageId=?,scannedAt=?,scannedByOperatorId=?,updatedAt=? WHERE id=?").run(packageId,now,operatorId,now,panelId);this.recalculate(packageId,now);this.event(pack.loadId,panelId,packageId,"PANEL_ADDED_TO_PACKAGE",operatorId,now);return this.findPackage(packageId)!;}
 removePanel(packageId:string,panelId:string,operatorId:string):PackageRecord{const pack=this.findPackage(packageId)!,now=new Date().toISOString();this.database.prepare("UPDATE Panels SET stato='MANCANTE',packageId=NULL,scannedAt=NULL,scannedByOperatorId=NULL,updatedAt=? WHERE id=? AND packageId=?").run(now,panelId,packageId);this.recalculate(packageId,now);this.event(pack.loadId,panelId,packageId,"PANEL_REMOVED_FROM_PACKAGE",operatorId,now);return this.findPackage(packageId)!;}
 closePackage(id:string,code:string,dimensions:{length:number;width:number;height:number},operatorId:string):PackageRecord{const pack=this.findPackage(id)!,now=new Date().toISOString();this.database.prepare("UPDATE Packages SET codicePacco=?,stato='DISPONIBILE',lunghezzaPacco=?,larghezzaPacco=?,altezzaPacco=?,operatoreId=?,closedAt=?,updatedAt=? WHERE id=?").run(code,dimensions.length,dimensions.width,dimensions.height,operatorId,now,now,id);this.database.prepare("UPDATE Panels SET stato='DISPONIBILE',updatedAt=? WHERE packageId=?").run(now,id);this.event(pack.loadId,null,id,"PACKAGE_CLOSED",operatorId,now);return this.findPackage(id)!;}
 cancelSingle(id:string,operatorId:string|null):void{const current=this.findPanel(id)!,now=new Date().toISOString();this.database.prepare("UPDATE Panels SET stato='MANCANTE',packageId=NULL,scannedAt=NULL,scannedByOperatorId=NULL,updatedAt=? WHERE id=?").run(now,id);this.event(current.loadId,id,null,"SCAN_CANCELLED",operatorId,now);}
 cancelPackage(id:string,operatorId:string|null):void{const pack=this.findPackage(id)!,now=new Date().toISOString();this.database.prepare("UPDATE Panels SET stato='MANCANTE',packageId=NULL,scannedAt=NULL,scannedByOperatorId=NULL,updatedAt=? WHERE packageId=?").run(now,id);this.event(pack.loadId,null,id,"PACKAGE_CANCELLED",operatorId,now);this.database.prepare("DELETE FROM Packages WHERE id=?").run(id);}
 private withPanels(value:Omit<PackageRecord,"pannelli">):PackageRecord{return{...value,pannelli:this.database.prepare("SELECT * FROM Panels WHERE packageId=? ORDER BY numeroPannello").all(value.id).map(panel)};}
 private recalculate(id:string,now:string):void{this.database.prepare("UPDATE Packages SET numeroPannelli=(SELECT COUNT(*) FROM Panels WHERE packageId=?),pesoTotale=COALESCE((SELECT SUM(peso) FROM Panels WHERE packageId=?),0),volumeTotale=COALESCE((SELECT SUM(volume) FROM Panels WHERE packageId=?),0),updatedAt=? WHERE id=?").run(id,id,id,now,id);}
 private event(loadId:string,panelId:string|null,packageId:string|null,type:string,operatorId:string|null,timestamp:string):void{this.database.prepare("INSERT INTO OperationalEvents(id,loadId,panelId,packageId,type,operatorId,timestamp) VALUES(?,?,?,?,?,?,?)").run(crypto.randomUUID(),loadId,panelId,packageId,type,operatorId,timestamp);}
}
