import type { DatabaseSync } from "node:sqlite";
import type { Trailer, TrailerInput } from "../models/settings.js";
import { booleanFromDatabase, requiredNumber, requiredString } from "./repositoryUtils.js";

const textOrNull=(value:unknown)=>typeof value==="string"?value:null;
const mapRow=(value:unknown):Trailer=>{const row=value as Record<string,unknown>;return{id:requiredString(row,"id"),plate:requiredString(row,"plate"),description:requiredString(row,"description"),notes:requiredString(row,"notes"),archived:booleanFromDatabase(row.archived),hasHistory:booleanFromDatabase(row.hasHistory),active:booleanFromDatabase(row.active),sortOrder:requiredNumber(row,"sortOrder"),nextInspectionDate:textOrNull(row.nextInspectionDate),disabled:booleanFromDatabase(row.disabled),disabledReason:textOrNull(row.disabledReason),disabledAt:textOrNull(row.disabledAt),createdAt:requiredString(row,"createdAt"),updatedAt:requiredString(row,"updatedAt")};};
export class TrailerRepository{
 constructor(private readonly database:DatabaseSync){}
 list():Trailer[]{return this.database.prepare("SELECT t.*, (EXISTS(SELECT 1 FROM TransportAssignments a WHERE a.trailerId=t.id) OR EXISTS(SELECT 1 FROM LoadingSessions s WHERE s.trailerId=t.id) OR EXISTS(SELECT 1 FROM ShipmentPlans p WHERE p.trailerId=t.id)) AS hasHistory FROM Trailers t ORDER BY sortOrder, plate").all().map(mapRow);}
 find(id:string):Trailer|null{const row=this.database.prepare("SELECT t.*, (EXISTS(SELECT 1 FROM TransportAssignments a WHERE a.trailerId=t.id) OR EXISTS(SELECT 1 FROM LoadingSessions s WHERE s.trailerId=t.id) OR EXISTS(SELECT 1 FROM ShipmentPlans p WHERE p.trailerId=t.id)) AS hasHistory FROM Trailers t WHERE t.id=?").get(id);return row?mapRow(row):null;}
 create(input:TrailerInput):Trailer{const id=input.id??crypto.randomUUID();const now=new Date().toISOString();this.database.prepare("INSERT INTO Trailers (id,plate,description,notes,active,sortOrder,nextInspectionDate,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)").run(id,input.plate,input.description,input.notes??"",input.active===false?0:1,input.sortOrder??0,input.nextInspectionDate??null,now,now);return this.find(id)!;}
 update(id:string,input:TrailerInput):Trailer|null{const current=this.find(id);if(!current)return null;if((current.hasHistory||current.archived)&&current.plate!==input.plate)throw new Error("TRAILER_PLATE_IMMUTABLE");this.database.prepare("UPDATE Trailers SET plate=?,description=?,notes=?,active=?,sortOrder=?,nextInspectionDate=?,updatedAt=? WHERE id=?").run(input.plate,input.description,input.notes??"",current.archived?0:input.active===false?0:1,input.sortOrder??0,input.nextInspectionDate??null,new Date().toISOString(),id);return this.find(id);}
 setActive(id:string,active:boolean):Trailer|null{const current=this.find(id);if(!current)return null;if(current.archived)throw new Error("TRAILER_ARCHIVED");this.database.prepare("UPDATE Trailers SET active=?,updatedAt=? WHERE id=?").run(active?1:0,new Date().toISOString(),id);return this.find(id);}
 remove(id:string):Trailer|null{const current=this.find(id);if(!current)return null;const active=this.database.prepare("SELECT 1 FROM TransportAssignments WHERE trailerId=? AND releasedAt IS NULL").get(id);if(active)throw new Error("TRAILER_IN_USE");this.database.prepare("UPDATE Trailers SET archived=1,active=0,disabled=0,disabledReason=NULL,disabledAt=NULL,updatedAt=? WHERE id=?").run(new Date().toISOString(),id);return this.find(id);}
}
