import type{DatabaseSync}from"node:sqlite";
export type TransportStatus="DISPONIBILE"|"IMPEGNATO"|"IN_VIAGGIO"|"FUORI_SERVIZIO";
export interface TransportRecord{id:string;plate:string;description:string;active:boolean;status:TransportStatus;commessa:string|null;cliente:string|null;camion:string|null;departedAt:string|null;availableFrom:string|null;nextInspectionDate:string|null;disabledReason:string|null;loadingSessionId:string|null;}
const nullable=(value:unknown)=>typeof value==="string"?value:null;
export class TransportRepository{constructor(private readonly db:DatabaseSync){}
 transaction<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const result=fn();this.db.exec("COMMIT");return result;}catch(error){this.db.exec("ROLLBACK");throw error;}}
 refreshExpired(now=new Date().toISOString()):void{this.db.prepare("UPDATE TransportAssignments SET stato='CONCLUSO',releasedAt=?,updatedAt=? WHERE releasedAt IS NULL AND stato='IN_VIAGGIO' AND availableFrom IS NOT NULL AND availableFrom<=?").run(now,now,now);}
 list():TransportRecord[]{this.refreshExpired();return this.db.prepare("SELECT t.*,a.stato assignmentStatus,a.departedAt,a.availableFrom,a.loadingSessionId,l.commessa,l.cliente,l.camion FROM Trailers t LEFT JOIN TransportAssignments a ON a.trailerId=t.id AND a.releasedAt IS NULL LEFT JOIN Loads l ON l.id=a.loadId ORDER BY t.sortOrder,t.plate").all().map(this.map);}
 find(id:string):TransportRecord|null{return this.list().find(item=>item.id===id)??null;}
 setInspection(id:string,date:string|null):TransportRecord|null{const result=this.db.prepare("UPDATE Trailers SET nextInspectionDate=?,updatedAt=? WHERE id=?").run(date,new Date().toISOString(),id);return result.changes?this.find(id):null;}
 disable(id:string,reason:string,notes:string):TransportRecord|null{const now=new Date().toISOString(),label=notes.trim()?`${reason}: ${notes.trim()}`:reason;const result=this.db.prepare("UPDATE Trailers SET disabled=1,disabledReason=?,disabledAt=?,updatedAt=? WHERE id=?").run(label,now,now,id);return result.changes?this.find(id):null;}
 enable(id:string):TransportRecord|null{const current=this.find(id);if(!current)return null;if(current.loadingSessionId)throw new Error("TRAILER_IN_USE");this.db.prepare("UPDATE Trailers SET disabled=0,disabledReason=NULL,disabledAt=NULL,active=1,updatedAt=? WHERE id=?").run(new Date().toISOString(),id);return this.find(id);}
 assign(trailerId:string,loadId:string,sessionId:string):void{const now=new Date().toISOString(),existing=this.db.prepare("SELECT id,trailerId FROM TransportAssignments WHERE loadId=? AND releasedAt IS NULL").get(loadId) as {id:string;trailerId:string}|undefined;if(existing?.trailerId===trailerId){this.db.prepare("UPDATE TransportAssignments SET loadingSessionId=?,updatedAt=? WHERE id=?").run(sessionId,now,existing.id);return;}if(existing)this.releaseByLoad(loadId,now);this.db.prepare("INSERT INTO TransportAssignments(id,trailerId,loadId,loadingSessionId,stato,assignedAt,createdAt,updatedAt)VALUES(?,?,?,?,'IMPEGNATO',?,?,?)").run(crypto.randomUUID(),trailerId,loadId,sessionId,now,now,now);}
 departBySession(sessionId:string,departedAt:string):void{const availableFrom=addBusinessDays(departedAt,2);this.db.prepare("UPDATE TransportAssignments SET stato='IN_VIAGGIO',departedAt=?,availableFrom=?,updatedAt=? WHERE loadingSessionId=? AND releasedAt IS NULL").run(departedAt,availableFrom,departedAt,sessionId);}
 releaseByLoad(loadId:string,at=new Date().toISOString()):void{this.db.prepare("UPDATE TransportAssignments SET stato='CONCLUSO',releasedAt=?,updatedAt=? WHERE loadId=? AND releasedAt IS NULL").run(at,at,loadId);}
 isAvailable(id:string,loadId?:string):boolean{const item=this.find(id);return Boolean(item&&item.active&&item.status!=="FUORI_SERVIZIO"&&(item.status==="DISPONIBILE"||(loadId&&item.loadingSessionId&&item.commessa&&this.db.prepare("SELECT 1 FROM TransportAssignments WHERE trailerId=? AND loadId=? AND releasedAt IS NULL").get(id,loadId))));}
 private map=(value:unknown):TransportRecord=>{const row=value as Record<string,unknown>;const disabled=Boolean(row.disabled)||!Boolean(row.active),assignment=nullable(row.assignmentStatus);const status:TransportStatus=disabled?"FUORI_SERVIZIO":assignment==="IN_VIAGGIO"?"IN_VIAGGIO":assignment?"IMPEGNATO":"DISPONIBILE";return{id:String(row.id),plate:String(row.plate),description:String(row.description),active:Boolean(row.active),status,commessa:nullable(row.commessa),cliente:nullable(row.cliente),camion:nullable(row.camion),departedAt:nullable(row.departedAt),availableFrom:nullable(row.availableFrom),nextInspectionDate:nullable(row.nextInspectionDate),disabledReason:nullable(row.disabledReason),loadingSessionId:nullable(row.loadingSessionId)};};}
export const addBusinessDays=(iso:string,days:number):string=>{const date=new Date(iso);let added=0;while(added<days){date.setUTCDate(date.getUTCDate()+1);const day=date.getUTCDay();if(day!==0&&day!==6)added++;}return date.toISOString();};
