import type { FastifyPluginAsync } from "fastify";
import { LoadController } from "../controllers/loadController.js";
import type { LoadService } from "../services/loadService.js";
import { idParamsSchema } from "./routeSchemas.js";
interface Options{service:LoadService}
const panelProperties={numeroPannello:{type:"string",minLength:1,maxLength:100},numeroCliente:{type:"string",maxLength:100},numeroMasterPanel:{type:"string",maxLength:100},camion:{type:"string",minLength:1,maxLength:100},lato1:{type:"string",maxLength:100},lato2:{type:"string",maxLength:100},tipoPannello:{type:"string",maxLength:100},quantita:{type:"number"},spessore:{type:"number"},lunghezza:{type:"number"},altezza:{type:"number"},superficie:{type:"number"},volume:{type:"number"},peso:{type:"number"}} as const;
const panelSchema={type:"object",additionalProperties:false,required:Object.keys(panelProperties),properties:panelProperties} as const;
export const importSchema={type:"object",additionalProperties:false,required:["commessa","cliente","numeroCliente","riferimentoOrdine","pannelli"],properties:{commessa:{type:"string",minLength:1,maxLength:100},cliente:{type:"string",maxLength:300},numeroCliente:{type:"string",maxLength:100},riferimentoOrdine:{type:"string",maxLength:300},removeMissing:{type:"boolean"},pannelli:{type:"array",minItems:1,items:panelSchema}}} as const;
export const loadRoutes:FastifyPluginAsync<Options>=async(app,options)=>{const controller=new LoadController(options.service);app.get("",controller.list);app.get("/:id",{schema:{params:idParamsSchema}},controller.get);app.get("/:id/panels",{schema:{params:idParamsSchema}},controller.panels);app.post("/import",{schema:{body:importSchema}},controller.import);app.put("/:id/import",{schema:{params:idParamsSchema,body:importSchema}},controller.updateImport);app.delete("/:id",{schema:{params:idParamsSchema}},controller.delete);};
