import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import { Box, Button, Chip, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography, useMediaQuery, useTheme } from "@mui/material";
import type { Camion } from "../models/Camion";
import type { Pacco } from "../models/Scanning";

interface Props { rows:Camion[]; packages:Pacco[]; activeSessions:Set<string>; onBack:()=>void; onOpen:(row:Camion)=>void; }
const sessionKey=(row:Camion)=>`${row.commessa}\u0000${row.camion}`;
export default function ActiveLoads({rows,packages,activeSessions,onBack,onOpen}:Props){
  const theme=useTheme();
  const narrowPhone=useMediaQuery(theme.breakpoints.down("sm"));
  const landscapePhone=useMediaQuery("(max-width:950px) and (max-height:500px)");
  const mobile=narrowPhone||landscapePhone;
  const active=rows.filter(row=>row.stato!=="Partita");
  const header=mobile?<Stack direction="row" sx={{alignItems:"center",gap:1,mb:1.5}}><Button size="small" startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h5" sx={{fontWeight:800,minWidth:0}}>Scansione elementi</Typography></Stack>:<Box sx={{display:"flex",alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Scansione elementi</Typography></Box>;
  return <Box sx={mobile?{mx:-1,overflowX:"hidden",pb:2}:undefined}>{header}{mobile?<Stack sx={{gap:1.25,px:1}}>{active.map(row=>{const started=activeSessions.has(sessionKey(row));const packs=packages.filter(pack=>pack.commessa===row.commessa&&pack.camion===row.camion).length;return <Paper key={row.id} variant="outlined" sx={{boxSizing:"border-box",p:1.5,width:"100%"}}><Stack direction="row" sx={{alignItems:"flex-start",justifyContent:"space-between",gap:1}}><Box sx={{minWidth:0}}><Typography sx={{fontSize:"1.08rem",fontWeight:900}}>Commessa {row.commessa}</Typography><Typography sx={{fontWeight:700,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{row.cliente}</Typography><Typography color="text.secondary" variant="body2">Camion {row.camion}</Typography></Box><Chip color={started?"warning":"default"} label={started?"In corso":row.stato} size="small" variant="outlined"/></Stack><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:.75,mt:1.5}}>{[["Previsti",row.previsti],["Disponibili",row.pronti],["Mancanti",row.mancanti]].map(([label,value])=><Box key={String(label)} sx={{minWidth:0,textAlign:"center"}}><Typography sx={{fontWeight:900,lineHeight:1.2}}>{value}</Typography><Typography color="text.secondary" variant="caption" sx={{display:"block",lineHeight:1.2}}>{label}</Typography></Box>)}</Box><Typography color="text.secondary" variant="body2" sx={{mt:1.25}}>Pacchi: {packs}</Typography><Button fullWidth size="large" startIcon={<PlayArrowIcon/>} sx={{mt:1.5}} variant="contained" onClick={()=>onOpen(row)}>Apri scansione</Button></Paper>})}{!active.length&&<Typography color="text.secondary" sx={{py:4,textAlign:"center"}}>Nessuna lista di carico attiva</Typography>}</Stack>:<Paper sx={{p:2}}><Typography variant="h6" sx={{mb:1.5}}>Liste di carico attive</Typography><Table><TableHead><TableRow>{["Commessa","Cliente","Camion","Previsti","Disponibili","Mancanti","Pacchi creati","Stato","Operazione"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{active.map(row=>{const started=activeSessions.has(sessionKey(row));const packs=packages.filter(pack=>pack.commessa===row.commessa&&pack.camion===row.camion).length;return <TableRow hover key={row.id} onClick={()=>onOpen(row)} sx={{cursor:"pointer"}}><TableCell>{row.commessa}</TableCell><TableCell>{row.cliente}</TableCell><TableCell>{row.camion}</TableCell><TableCell>{row.previsti}</TableCell><TableCell>{row.pronti}</TableCell><TableCell>{row.mancanti}</TableCell><TableCell>{packs}</TableCell><TableCell><Chip label={row.stato} size="small" variant="outlined"/></TableCell><TableCell><Button startIcon={<PlayArrowIcon/>} variant="outlined" onClick={event=>{event.stopPropagation();onOpen(row);}}>{started?"Continua":"Apri scansione"}</Button></TableCell></TableRow>})}</TableBody></Table>{!active.length&&<Typography color="text.secondary" sx={{py:4,textAlign:"center"}}>Nessuna lista di carico attiva</Typography>}</Paper>}</Box>;
}
