import { useMemo, useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import { Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Paper,Snackbar,Stack as MuiStack,Table,TableBody,TableCell,TableHead,TableRow,TableSortLabel,TextField,Typography as MuiTypography } from "@mui/material";
import PackagePrintPreview from "../components/scanning/PackagePrintPreview";
import type { CaricoCamion } from "../models/Loading";
import type { Pacco,UnitaSingola } from "../models/Scanning";
import type { SettingsData } from "../models/Settings";
import type { Commessa } from "../types/excel";
import { exportHistoryCsv,loadPackages,loadSingles,matchesHistory,shipmentDate,shippedLoads,timeline,totals } from "../services/historyService";

interface Props{loads:CaricoCamion[];packages:Pacco[];singles:UnitaSingola[];commesse:Commessa[];settings:SettingsData;initialLoadId?:string;onBack:()=>void}
const Stack=(props:React.ComponentProps<typeof MuiStack>&Record<string,unknown>)=><MuiStack {...props}/>;
const Typography=(props:React.ComponentProps<typeof MuiTypography>&Record<string,unknown>)=><MuiTypography {...props}/>;
type SortKey="date"|"commessa"|"cliente"|"camion"|"panels"|"packs"|"weight"|"volume";
const dt=(value?:string)=>value?new Date(value).toLocaleString("it-IT"):"—";
const eventLabels:Record<string,string>={AVVIO:"Avvio carico",SCANSIONE:"Scansione di carico",CHIUSURA:"Prima chiusura",RIAPERTURA:"Riapertura carico",UNITA_AGGIUNTA:"Unità aggiunta",UNITA_RIMOSSA:"Unità rimossa",NUOVA_CHIUSURA:"Nuova chiusura",PARTENZA:"Conferma partenza"};

export default function History({loads,packages,singles,commesse,settings,initialLoadId,onBack}:Props){
 const [search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[client,setClient]=useState(""),[carrier,setCarrier]=useState(""),[trailer,setTrailer]=useState(""),[operator,setOperator]=useState(""),[year,setYear]=useState("");
 const [sort,setSort]=useState<SortKey>("date"),[asc,setAsc]=useState(false),[detail,setDetail]=useState<CaricoCamion|null>(()=>loads.find(load=>load.loadId===initialLoadId&&load.stato==="SPEDITO")??null),[oldestFirst,setOldestFirst]=useState(false),[printPack,setPrintPack]=useState<Pacco|null>(null),[notice,setNotice]=useState<string|null>(null);
 const carrierName=(id?:string)=>settings.trasportatori.find(x=>x.id===id)?.nome??"—";const trailerName=(id?:string)=>{const x=settings.rimorchi.find(x=>x.id===id);return x?`${x.targa} — ${x.descrizione}`:"—";};
 const all=useMemo(()=>shippedLoads(loads),[loads]);
 const visible=useMemo(()=>all.filter(l=>{const d=shipmentDate(l).slice(0,10);return matchesHistory(l,search,packages)&&(!from||d>=from)&&(!to||d<=to)&&(!client||l.cliente===client)&&(!carrier||l.trasportatoreId===carrier)&&(!trailer||l.rimorchioId===trailer)&&(!operator||l.operatoreId===operator)&&(!year||d.startsWith(year));}).sort((a,b)=>{const ta=totals(a,packages,singles,commesse),tb=totals(b,packages,singles,commesse);const av=sort==="date"?shipmentDate(a):sort==="commessa"?a.commessa:sort==="cliente"?a.cliente:sort==="camion"?a.camion:sort==="panels"?ta.panels:sort==="packs"?ta.packs:sort==="weight"?ta.weight:ta.volume;const bv=sort==="date"?shipmentDate(b):sort==="commessa"?b.commessa:sort==="cliente"?b.cliente:sort==="camion"?b.camion:sort==="panels"?tb.panels:sort==="packs"?tb.packs:sort==="weight"?tb.weight:tb.volume;return (typeof av==="number"?av-(bv as number):String(av).localeCompare(String(bv),"it"))*(asc?1:-1);}),[all,search,from,to,client,carrier,trailer,operator,year,sort,asc,packages,singles,commesse]);
 const reset=()=>{setSearch("");setFrom("");setTo("");setClient("");setCarrier("");setTrailer("");setOperator("");setYear("");};
 const sortable=(label:string,key:SortKey)=><TableCell><TableSortLabel active={sort===key} direction={sort===key&&asc?"asc":"desc"} onClick={()=>{if(sort===key)setAsc(x=>!x);else{setSort(key);setAsc(true);}}}>{label}</TableSortLabel></TableCell>;
 const exportCsv=()=>{const blob=new Blob(["\ufeff"+exportHistoryCsv(visible,packages,singles,commesse,carrierName,trailerName)],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`storico-spedizioni-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);setNotice("CSV esportato con i filtri attivi");};
 const detailPacks=detail?loadPackages(detail,packages):[],detailSingles=detail?loadSingles(detail,singles,commesse,packages):[],detailTotals=detail?totals(detail,packages,singles,commesse):null;
 const shippedPanelRows=[...detailSingles.map(({unit,panel})=>({key:`single-${unit.commessa}-${unit.camion}-${panel.numeroPannello}`,type:"Singolo",packageCode:"",panel,operator:unit.operatore,scannedAt:unit.chiusaIl})),...detailPacks.flatMap(pack=>pack.pannelli.map(panel=>({key:`package-${pack.codice}-${panel.numeroPannello}`,type:"Pacco",packageCode:pack.codice,panel,operator:pack.operatore,scannedAt:pack.chiusoIl})) )];
 const shippedPanelsSection=<Paper sx={{p:2,mb:2,overflowX:"auto"}}><Typography variant="h6" sx={{mb:1.5}}>Tutti i pannelli spediti</Typography><Table size="small" sx={{minWidth:1280}}><TableHead><TableRow>{["Tipo unità","Codice pacco","Numero pannello","Master panel","Spessore","Dimensioni","Peso","Volume","Operatore scansione","Data scansione","Stato"].map(label=><TableCell key={label} sx={{whiteSpace:"nowrap"}}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{shippedPanelRows.map(row=><TableRow key={row.key} hover><TableCell>{row.type}</TableCell><TableCell>{row.packageCode&&<Button size="small" sx={{fontWeight:800,p:0,minWidth:0}} onClick={()=>setPrintPack(detailPacks.find(pack=>pack.codice===row.packageCode)??null)}>{row.packageCode}</Button>}</TableCell><TableCell>{row.panel.numeroPannello}</TableCell><TableCell>{row.panel.numeroMasterPanel}</TableCell><TableCell>{row.panel.spessore} mm</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{row.panel.lunghezza} × {row.panel.altezza} mm</TableCell><TableCell>{row.panel.peso.toFixed(1)} kg</TableCell><TableCell>{row.panel.volume.toFixed(3)} m³</TableCell><TableCell>{row.operator}</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{dt(row.scannedAt)}</TableCell><TableCell><Chip color="success" label="SPEDITO" size="small" variant="outlined"/></TableCell></TableRow>)}</TableBody></Table></Paper>;
 return <Box><Stack direction={{xs:"column",sm:"row"}} sx={{gap:1,alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>STORICO SPEDIZIONI</Typography><Button variant="contained" onClick={exportCsv}>Esporta CSV</Button></Stack>
 <Paper sx={{p:2,mb:2}}><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"2fr repeat(4,1fr)"},gap:1}}><TextField label="Cerca commessa, cliente, camion, pacco o pannello" value={search} onChange={e=>setSearch(e.target.value)}/><TextField type="date" label="Data da" value={from} onChange={e=>setFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Data a" value={to} onChange={e=>setTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField select label="Cliente" value={client} onChange={e=>setClient(e.target.value)}><MenuItem value="">Tutti</MenuItem>{[...new Set(all.map(x=>x.cliente))].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Trasportatore" value={carrier} onChange={e=>setCarrier(e.target.value)}><MenuItem value="">Tutti</MenuItem>{settings.trasportatori.map(x=><MenuItem key={x.id} value={x.id}>{x.nome}</MenuItem>)}</TextField><TextField select label="Rimorchio Essepi" value={trailer} onChange={e=>setTrailer(e.target.value)}><MenuItem value="">Tutti</MenuItem>{settings.rimorchi.map(x=><MenuItem key={x.id} value={x.id}>{x.targa}</MenuItem>)}</TextField><TextField select label="Operatore" value={operator} onChange={e=>setOperator(e.target.value)}><MenuItem value="">Tutti</MenuItem>{settings.operatori.map(x=><MenuItem key={x.id} value={x.id}>{x.nome} {x.cognome}</MenuItem>)}</TextField><TextField select label="Anno" value={year} onChange={e=>setYear(e.target.value)}><MenuItem value="">Tutti</MenuItem>{[...new Set(all.map(x=>shipmentDate(x).slice(0,4)))].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Button onClick={reset}>Reimposta filtri</Button></Box></Paper>
 <Paper sx={{overflowX:"auto"}}><Table size="small"><TableHead><TableRow>{sortable("Data spedizione","date")}{sortable("Commessa","commessa")}{sortable("Cliente","cliente")}{sortable("Camion","camion")}<TableCell>Trasportatore</TableCell><TableCell>Rimorchio Essepi</TableCell>{sortable("Pannelli spediti","panels")}{sortable("Pacchi spediti","packs")}{sortable("Peso totale","weight")}{sortable("Volume totale","volume")}<TableCell>Operatore partenza</TableCell><TableCell>Stato</TableCell><TableCell>Operazioni</TableCell></TableRow></TableHead><TableBody>{visible.map(l=>{const t=totals(l,packages,singles,commesse);return <TableRow hover key={l.loadId}><TableCell>{dt(shipmentDate(l))}</TableCell><TableCell>{l.commessa}</TableCell><TableCell>{l.cliente}</TableCell><TableCell>{l.camion}</TableCell><TableCell>{carrierName(l.trasportatoreId)}</TableCell><TableCell>{trailerName(l.rimorchioId)}</TableCell><TableCell>{t.panels}</TableCell><TableCell>{t.packs}</TableCell><TableCell>{t.weight.toFixed(1)} kg</TableCell><TableCell>{t.volume.toFixed(3)} m³</TableCell><TableCell>{l.operatore}</TableCell><TableCell><Chip color="success" size="small" label="Spedito"/></TableCell><TableCell><Button size="small" onClick={()=>setDetail(l)}>Apri dettaglio</Button></TableCell></TableRow>})}</TableBody></Table>{!visible.length&&<Typography textAlign="center" color="text.secondary" py={5}>Nessuna spedizione trovata</Typography>}</Paper>
 <Dialog fullScreen open={!!detail} onClose={()=>setDetail(null)}><DialogTitle>Spedizione {detail?.commessa} · {detail?.camion} <Chip color="success" label="Spedito" size="small"/></DialogTitle><DialogContent>{detail&&<><Paper sx={{p:2,mb:2}}><Typography variant="h6">Dati generali</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",md:"repeat(4,1fr)"},gap:1,mt:1}}>{[["Commessa",detail.commessa],["Cliente",detail.cliente],["Camion",detail.camion],["Stato","Spedito"],["Trasportatore",carrierName(detail.trasportatoreId)],["Rimorchio Essepi",trailerName(detail.rimorchioId)],["Avvio carico",dt(detail.avviatoIl)],["Completamento",dt(detail.completatoIl)],["Spedizione",dt(shipmentDate(detail))],["Operatore avvio",timeline(detail).find(x=>x.tipo==="AVVIO")?.operatore??"—"],["Operatore chiusura",[...timeline(detail)].find(x=>x.tipo==="CHIUSURA"||x.tipo==="NUOVA_CHIUSURA")?.operatore??"—"],["Operatore partenza",detail.operatore]].map(([k,v])=><Box key={k}><Typography variant="caption" color="text.secondary">{k}</Typography><Typography>{v}</Typography></Box>)}</Box></Paper>
 <Paper sx={{p:2,mb:2}}><Typography variant="h6">Riepilogo</Typography><Stack direction="row" flexWrap="wrap" gap={4} mt={1}>{[["Pannelli previsti",commesse.find(c=>c.ordine===detail.commessa)?.pannelli.filter(p=>p.numeroCamion===detail.camion).length??detailTotals?.panels],["Pannelli spediti",detailTotals?.panels],["Pacchi spediti",detailTotals?.packs],["Peso totale",`${detailTotals?.weight.toFixed(1)} kg`],["Volume totale",`${detailTotals?.volume.toFixed(3)} m³`]].map(([k,v])=><Box key={k}><Typography variant="caption" color="text.secondary">{k}</Typography><Typography variant="h6">{v}</Typography></Box>)}</Stack></Paper>
 {shippedPanelsSection}<Paper sx={{p:2}}><Stack direction="row" justifyContent="space-between"><Typography variant="h6">Cronologia eventi</Typography><Button onClick={()=>setOldestFirst(x=>!x)}>{oldestFirst?"Più recenti prima":"Più vecchi prima"}</Button></Stack>{(oldestFirst?[...timeline(detail)].reverse():timeline(detail)).map((e,i)=><Box key={`${e.dataOra}-${i}`} sx={{py:1,borderBottom:1,borderColor:"divider"}}><Typography><b>{dt(e.dataOra)}</b> · {eventLabels[e.tipo]??e.tipo} · {e.operatore}</Typography><Typography color="text.secondary">{e.nota??eventLabels[e.tipo]??e.tipo}</Typography></Box>)}</Paper></>}</DialogContent><DialogActions><Button onClick={()=>setDetail(null)}>Chiudi</Button></DialogActions></Dialog>
 <Dialog fullWidth maxWidth="lg" open={!!printPack} onClose={()=>setPrintPack(null)}><DialogTitle>Dettaglio pacco {printPack?.codice}</DialogTitle><DialogContent sx={{"& .package-print > .no-print":{display:"none"}}}>{printPack&&<PackagePrintPreview pack={printPack}/>}</DialogContent><DialogActions><Button onClick={()=>setPrintPack(null)}>Chiudi</Button><Button variant="contained" onClick={()=>window.print()}>Ristampa etichetta pacco</Button></DialogActions></Dialog><Snackbar open={!!notice} autoHideDuration={3500} onClose={()=>setNotice(null)}><Alert severity="success">{notice}</Alert></Snackbar></Box>;
}
