import { useEffect, useMemo, useRef, useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import UndoIcon from "@mui/icons-material/Undo";
import WidgetsOutlinedIcon from "@mui/icons-material/WidgetsOutlined";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography, useMediaQuery, useTheme } from "@mui/material";
import ScannerInput from "../components/scanning/ScannerInput";
import PackagePrintPreview from "../components/scanning/PackagePrintPreview";
import type { Camion } from "../models/Camion";
import type { Pacco, UnitaSingola } from "../models/Scanning";
import type { Operatore } from "../models/Settings";
import { operatorLabel } from "../models/Settings";
import type { Commessa, Pannello } from "../types/excel";
import { nextPackageCode, packageVolume, packageWeight, parseOperationalQr, parsePanelQr } from "../utils/panelQr";
import { buildPanelKey } from "../utils/panelIdentity";
import { addPanelToPackage, cancelPanelApi, closePackageApi, closeSinglePanel, createPackage, removePanelFromPackage, scanPanel } from "../services/scanningApi";

interface Props { target:Camion; commessa:Commessa; packages:Pacco[]; singles:UnitaSingola[]; operators:Operatore[]; draftPanels:Pannello[]; draftId?:string; onDraftChange:React.Dispatch<React.SetStateAction<Pannello[]>>; onDataChanged:()=>Promise<void>; onBack:()=>void; onCloseSingle:(unit:UnitaSingola)=>void; onClosePackage:(pack:Pacco)=>void; }
type Mode="single"|"package";
type Result={severity:"success"|"error"|"info";message:string}|null;
type PanelSituation="MANCANTE"|"IN PACCO"|"DISPONIBILE"|"CARICATO";

export default function PanelScanning({target,commessa,packages,singles,operators,draftPanels,draftId,onDraftChange,onDataChanged,onBack,onCloseSingle,onClosePackage}:Props){
  const theme=useTheme();
  const narrowPhone=useMediaQuery(theme.breakpoints.down("sm"));
  const landscapePhone=useMediaQuery("(max-width:950px) and (max-height:500px)");
  const mobile=narrowPhone||landscapePhone;
  const panels=useMemo(()=>commessa.pannelli.filter(p=>p.numeroCamion===target.camion),[commessa.pannelli,target.camion]);
  const [mode,setMode]=useState<Mode>(draftId?"package":"single"); const [operatorId,setOperatorId]=useState(""); const [result,setResult]=useState<Result>(null);
  const [scannerValue,setScannerValue]=useState("");
  const openPanels=draftPanels; const setOpenPanels=onDraftChange; const [closedPack,setClosedPack]=useState<Pacco|null>(null); const [removePanel,setRemovePanel]=useState<Pannello|null>(null);
  const [undoPanel,setUndoPanel]=useState<Pannello|null>(null);
  const [pendingPackageCode,setPendingPackageCode]=useState<string|null>(null);const [packageLength,setPackageLength]=useState("");const [packageWidth,setPackageWidth]=useState("");const [packageHeight,setPackageHeight]=useState("");
  const autoPrintedPackRef=useRef<string|null>(null);
  const available=panels.filter(p=>p.preparato).length; const createdPackages=packages.filter(p=>p.commessa===target.commessa&&p.camion===target.camion).length;
  const selectedOperator=operators.find(operator=>operator.id===operatorId);
  const panelKey=(panel:Pannello)=>buildPanelKey({commessa:target.commessa,cliente:target.cliente,camion:panel.numeroCamion,numeroPannello:panel.numeroPannello});
  const isInPackage=(value:Pannello|string)=>{const panel=typeof value==="string"?panels.find(item=>item.numeroPannello===value):value;return panel?packages.find(pack=>pack.pannelli.some(item=>buildPanelKey({commessa:pack.commessa,cliente:pack.cliente,camion:pack.camion,numeroPannello:item.numeroPannello})===panelKey(panel))):undefined;};
  const closePackage=()=>{if(!selectedOperator){setResult({severity:"error",message:"Seleziona un operatore prima di procedere."});return;}if(!openPanels.length){setResult({severity:"error",message:"Il pacco deve contenere almeno un pannello"});return;}setPendingPackageCode(nextPackageCode(packages));setPackageLength("");setPackageWidth("");setPackageHeight("");};
  const packageDimensionsValid=[packageLength,packageWidth,packageHeight].every(value=>Number.isFinite(Number(value))&&Number(value)>0);
  const confirmPackageClose=async()=>{if(!selectedOperator||!pendingPackageCode||!draftId||!openPanels.length||!packageDimensionsValid)return;try{await closePackageApi(draftId,{codicePacco:pendingPackageCode,operatoreId:selectedOperator.id,lunghezzaPacco:Number(packageLength),larghezzaPacco:Number(packageWidth),altezzaPacco:Number(packageHeight)});const pack:Pacco={id:draftId,codice:pendingPackageCode,stato:"DISPONIBILE",commessa:target.commessa,cliente:target.cliente,camion:target.camion,pannelli:openPanels,numeroPezzi:openPanels.length,pesoTotale:packageWeight(openPanels),volumeTotale:packageVolume(openPanels),lunghezzaPacco:Number(packageLength),larghezzaPacco:Number(packageWidth),altezzaPacco:Number(packageHeight),operatore:operatorLabel(selectedOperator),operatoreId:selectedOperator.id,chiusoIl:new Date().toISOString()};await onDataChanged();onClosePackage(pack);setClosedPack(pack);setOpenPanels([]);setPendingPackageCode(null);setMode("single");setResult({severity:"success",message:`Pacco ${pack.codice} chiuso e disponibile. Modalità pannello singolo attiva.`});}catch{setResult({severity:"error",message:"Errore durante la chiusura del pacco"});}};
  const scan=async(raw:string)=>{
    if(!selectedOperator){setResult({severity:"error",message:"Seleziona un operatore prima di procedere."});return;}
    const operation=parseOperationalQr(raw);if(operation==="CHIUDI_PACCO"){closePackage();return;}
    const qr=parsePanelQr(raw);if(!qr){setResult({severity:"error",message:"QR non valido"});return;}
    const scannedKey=buildPanelKey(qr);const panel=panels.find(p=>panelKey(p)===scannedKey);if(!panel){setResult({severity:"error",message:"Pannello non previsto nella commessa"});return;}
    if(panel.caricato){setResult({severity:"error",message:"Pannello già caricato"});return;}
    const pack=isInPackage(panel.numeroPannello);if(pack){setResult({severity:"error",message:`Pannello già inserito nel pacco ${pack.codice}`});return;}
    if(panel.preparato||singles.some(item=>item.commessa===target.commessa&&item.camion===target.camion&&item.numeroPannello===panel.numeroPannello)){setResult({severity:"error",message:"Pannello già registrato"});return;}
    if(openPanels.some(item=>item.numeroPannello===panel.numeroPannello)){setResult({severity:"error",message:"Pannello già registrato"});return;}
    if(!panel.backendId){setResult({severity:"error",message:"Identificativo pannello non disponibile"});return;}
    if(mode==="single"&&panel.scannedAt&&!panel.preparato&&!panel.packageId){try{await closeSinglePanel(panel.backendId,selectedOperator.id);await onDataChanged();onCloseSingle({tipo:"SINGOLO",commessa:target.commessa,camion:target.camion,numeroPannello:panel.numeroPannello,operatore:operatorLabel(selectedOperator),operatoreId:selectedOperator.id,chiusaIl:new Date().toISOString()});setResult({severity:"success",message:`Pannello ${panel.numeroPannello} registrato e disponibile`});}catch{setResult({severity:"error",message:`Chiusura automatica del pannello ${panel.numeroPannello} non riuscita. Il pannello non risulta disponibile.`});}return;}
    try{await scanPanel(panel.backendId,selectedOperator.id);if(mode==="single"){try{await closeSinglePanel(panel.backendId,selectedOperator.id);}catch{await onDataChanged();setResult({severity:"error",message:`Pannello ${panel.numeroPannello} acquisito, ma la chiusura automatica non è riuscita. Il pannello non risulta ancora disponibile.`});return;}await onDataChanged();onCloseSingle({tipo:"SINGOLO",commessa:target.commessa,camion:target.camion,numeroPannello:panel.numeroPannello,operatore:operatorLabel(selectedOperator),operatoreId:selectedOperator.id,chiusaIl:new Date().toISOString()});setResult({severity:"success",message:`Pannello ${panel.numeroPannello} registrato e disponibile`});}
    else {if(!draftId){setResult({severity:"error",message:"Pacco aperto non disponibile"});return;}await addPanelToPackage(draftId,panel.backendId,selectedOperator.id);setOpenPanels(current=>[...current,panel]);await onDataChanged();setResult({severity:"success",message:`Pannello ${panel.numeroPannello} aggiunto al pacco aperto`});}}catch{setResult({severity:"error",message:"Pannello non disponibile o già registrato"});}
  };
  const chooseMode=async(next:Mode)=>{if(openPanels.length&&mode!==next){setResult({severity:"error",message:"Chiudi il pacco corrente prima di cambiare modalità"});return;}if(next==="package"&&!draftId&&selectedOperator){const loadId=panels[0]?.loadId;if(!loadId){setResult({severity:"error",message:"Carico non disponibile nel database"});return;}try{await createPackage(loadId,selectedOperator.id);await onDataChanged();}catch{setResult({severity:"error",message:"Impossibile aprire il pacco"});return;}}setMode(next);setClosedPack(null);setResult({severity:"info",message:next==="single"?"Modalità pannello singolo attiva":"Nuovo pacco aperto"});};
  const submitScan=(raw:string)=>{setScannerValue("");void scan(raw);};
  const confirmRemovePanel=async()=>{if(!removePanel?.backendId||!draftId||!selectedOperator)return;try{await removePanelFromPackage(draftId,removePanel.backendId,selectedOperator.id);setOpenPanels(current=>current.filter(panel=>panel.backendId!==removePanel.backendId));setRemovePanel(null);await onDataChanged();}catch{setResult({severity:"error",message:"Impossibile rimuovere il pannello dal pacco"});}};
  const confirmUndoPanel=async()=>{if(!undoPanel?.backendId||!selectedOperator)return;const number=undoPanel.numeroPannello;try{await cancelPanelApi(undoPanel.backendId,selectedOperator.id);setUndoPanel(null);await onDataChanged();setResult({severity:"success",message:`Scansione del pannello ${number} annullata`});}catch{setResult({severity:"error",message:"Impossibile annullare la scansione: il pannello potrebbe essere già utilizzato"});}};
  const panelDetails=panels.map(panel=>{const closedPackage=isInPackage(panel),inOpenPackage=openPanels.some(open=>panelKey(open)===panelKey(panel)),singleAvailable=panel.preparato||singles.some(unit=>unit.commessa===target.commessa&&unit.camion===target.camion&&unit.numeroPannello===panel.numeroPannello),situation:PanelSituation=panel.caricato?"CARICATO":closedPackage||inOpenPackage?"IN PACCO":singleAvailable?"DISPONIBILE":"MANCANTE";return{panel,situation,packageLabel:closedPackage?.codice??(inOpenPackage?"Pacco aperto":null)};});
  const mobilePanels=[...panelDetails].sort((a,b)=>{const rank:Record<PanelSituation,number>={MANCANTE:0,"IN PACCO":1,DISPONIBILE:2,CARICATO:3};return rank[a.situation]-rank[b.situation]||a.panel.numeroPannello.localeCompare(b.panel.numeroPannello,"it",{numeric:true});});
  useEffect(()=>{if(draftId)setMode("package");},[draftId]);
  useEffect(()=>{if(!closedPack||autoPrintedPackRef.current===closedPack.codice)return;autoPrintedPackRef.current=closedPack.codice;window.print();},[closedPack]);
  if(mobile)return <Box sx={{mx:-1,pb:2,overflowX:"hidden"}}>
    <Stack direction="row" sx={{alignItems:"center",gap:1,mb:1.5,px:1}}><Button size="small" startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h5" sx={{fontWeight:800}}>Scansione pannelli</Typography></Stack>
    <Paper sx={{p:1.5,mx:1,mb:1.5}}>
      <Box sx={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:1,pb:1.25,borderBottom:1,borderColor:"divider"}}>{[["Commessa",target.commessa],["Cliente",target.cliente],["Camion",target.camion]].map(([label,value])=><Box key={label} sx={{minWidth:0}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography sx={{fontWeight:800,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{value}</Typography></Box>)}</Box>
      <Box sx={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:.5,pt:1.25}}>{[["Previsti",panels.length],["Disponibili",available],["Mancanti",panels.length-available],["Pacchi",createdPackages]].map(([label,value])=><Box key={label} sx={{textAlign:"center",minWidth:0}}><Typography sx={{fontWeight:900,fontSize:"1.15rem",lineHeight:1.1}}>{value}</Typography><Typography variant="caption" color="text.secondary" sx={{fontSize:".68rem"}}>{label}</Typography></Box>)}</Box>
    </Paper>
    <Paper sx={{p:1.5,mx:1,mb:1.5}}>
      <TextField select required fullWidth label="Operatore" value={operatorId} onChange={e=>{setOperatorId(e.target.value);if(mode!=="package")setMode("single");}} sx={{mb:1.25}}><MenuItem value="" disabled>Seleziona operatore</MenuItem>{operators.map(operator=><MenuItem key={operator.id} value={operator.id}>{operatorLabel(operator)}</MenuItem>)}</TextField>
      <ScannerInput mobileEmphasis disabled={!selectedOperator} value={scannerValue} onValueChange={setScannerValue} onScan={submitScan}/>
      {!selectedOperator&&<Alert severity="warning" sx={{mt:1.25}}>Seleziona un operatore per iniziare.</Alert>}
    </Paper>
    {mode!=="package"?<Button fullWidth size="large" variant="outlined" disabled={!selectedOperator} startIcon={<WidgetsOutlinedIcon/>} onClick={()=>void chooseMode("package")} sx={{mx:1,mb:1.5,width:"calc(100% - 16px)",minHeight:58}}>Apri nuovo pacco</Button>:<Paper sx={{p:1.5,mx:1,mb:1.5,border:2,borderColor:"warning.main",bgcolor:"rgba(255,152,0,.07)"}}>
      <Stack direction="row" sx={{alignItems:"flex-start",justifyContent:"space-between",gap:1,mb:1.25}}><Box><Typography variant="overline" color="warning.main" sx={{fontWeight:900,lineHeight:1}}>Pacco aperto</Typography><Typography sx={{fontWeight:800}}>{openPanels.length} pannelli</Typography><Typography variant="body2" color="text.secondary">{packageWeight(openPanels).toFixed(1)} kg · {packageVolume(openPanels).toFixed(3)} m³</Typography></Box><Chip label="MODALITÀ PACCO" color="warning" size="small"/></Stack>
      {!!openPanels.length&&<Stack sx={{gap:.5,mb:1.25}}>{openPanels.map(panel=><Stack key={panelKey(panel)} direction="row" sx={{alignItems:"center",justifyContent:"space-between",pl:1,bgcolor:"background.paper",borderRadius:1}}><Typography variant="body2">Pannello <b>{panel.numeroPannello}</b></Typography><IconButton color="error" size="small" onClick={()=>setRemovePanel(panel)}><DeleteOutlinedIcon fontSize="small"/></IconButton></Stack>)}</Stack>}
      <Button fullWidth size="large" variant="contained" color="warning" disabled={!openPanels.length} onClick={closePackage} sx={{minHeight:56}}>Chiudi pacco</Button>
    </Paper>}
    {result&&<Alert severity={result.severity} variant="filled" sx={{mx:1,mb:1.5,fontSize:"1rem",fontWeight:700,alignItems:"center"}}>{result.message}</Alert>}
    <Typography variant="h6" sx={{mx:1,mb:1}}>Pannelli previsti</Typography>
    <Stack sx={{gap:1,mx:1}}>{mobilePanels.map(({panel,situation,packageLabel})=>{const color=situation==="DISPONIBILE"?"success":situation==="IN PACCO"?"warning":situation==="CARICATO"?"info":"default";return <Paper key={panelKey(panel)} variant="outlined" sx={{p:1.25,borderColor:situation==="MANCANTE"?"divider":`${color}.main`}}><Stack direction="row" sx={{alignItems:"flex-start",justifyContent:"space-between",gap:1}}><Box sx={{minWidth:0}}><Typography sx={{fontWeight:900,fontSize:"1.05rem"}}>Pannello {panel.numeroPannello}</Typography><Typography variant="body2" color="text.secondary">MP {panel.numeroMasterPanel}</Typography></Box><Chip size="small" color={color} variant={situation==="MANCANTE"?"outlined":"filled"} label={situation}/></Stack><Box sx={{display:"grid",gridTemplateColumns:"1fr auto",alignItems:"end",gap:1,mt:1}}><Box><Typography variant="body2">{Math.round(panel.spessore)} × {Math.round(panel.lunghezza)} × {Math.round(panel.altezza)} mm</Typography><Typography variant="body2" sx={{fontWeight:700}}>{panel.peso.toFixed(1)} kg</Typography>{packageLabel&&<Typography variant="caption" color="warning.main">{packageLabel}</Typography>}</Box>{situation==="DISPONIBILE"&&<IconButton disabled={!selectedOperator} title="Annulla scansione" onClick={()=>setUndoPanel(panel)}><UndoIcon/></IconButton>}</Box></Paper>;})}</Stack>
    {closedPack&&<PackagePrintPreview pack={closedPack}/>}<Dialog open={pendingPackageCode!==null} onClose={()=>setPendingPackageCode(null)} fullScreen><DialogTitle>Dimensioni esterne pacco</DialogTitle><DialogContent><Stack sx={{gap:1.5,pt:1}}>{[["Codice pacco",pendingPackageCode??""],["Commessa",target.commessa],["Pannelli",openPanels.length],["Peso",`${packageWeight(openPanels).toFixed(1)} kg`],["Volume",`${packageVolume(openPanels).toFixed(3)} m³`]].map(([label,value])=><Box key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{value}</Typography></Box>)}<TextField autoFocus required type="number" label="Lunghezza pacco (mm)" value={packageLength} onChange={event=>setPackageLength(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/><TextField required type="number" label="Larghezza pacco (mm)" value={packageWidth} onChange={event=>setPackageWidth(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/><TextField required type="number" label="Altezza pacco (mm)" value={packageHeight} onChange={event=>setPackageHeight(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setPendingPackageCode(null)}>Annulla</Button><Button variant="contained" disabled={!packageDimensionsValid} onClick={confirmPackageClose}>Conferma chiusura</Button></DialogActions></Dialog>
    <Dialog open={removePanel!==null} onClose={()=>setRemovePanel(null)}><DialogTitle>Rimuovi pannello</DialogTitle><DialogContent><DialogContentText>Vuoi rimuovere il pannello {removePanel?.numeroPannello} dal pacco aperto?</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setRemovePanel(null)}>Annulla</Button><Button color="error" onClick={()=>void confirmRemovePanel()}>Rimuovi</Button></DialogActions></Dialog>
    <Dialog open={undoPanel!==null} onClose={()=>setUndoPanel(null)}><DialogTitle>Annulla scansione</DialogTitle><DialogContent><DialogContentText>Riportare il pannello {undoPanel?.numeroPannello} allo stato MANCANTE?</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setUndoPanel(null)}>Annulla</Button><Button variant="contained" onClick={()=>void confirmUndoPanel()}>Conferma</Button></DialogActions></Dialog>
  </Box>;
  return <Box>
    <Stack direction="row" sx={{alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Scansione pannello finito</Typography></Stack>
    <Box sx={{display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:1.5,mb:2}}>{[["Commessa",target.commessa],["Cliente",target.cliente],["Camion",target.camion],["Previsti",panels.length],["Disponibili",available],["Mancanti",panels.length-available],["Pacchi creati",createdPackages]].map(([label,value])=><Paper key={label} sx={{p:1.5,textAlign:"center"}}><Typography color="text.secondary" variant="caption">{label}</Typography><Typography variant="h6" sx={{fontWeight:800}}>{value}</Typography></Paper>)}</Box>
    <Paper sx={{p:2,mb:2}}><Stack direction={{xs:"column",sm:"row"}} sx={{alignItems:{xs:"stretch",sm:"center"},flexWrap:"wrap",gap:1.5,mb:1.5}}><TextField select required label="Operatore" value={operatorId} onChange={e=>{setOperatorId(e.target.value);if(mode!=="package")setMode("single");}} sx={{minWidth:{xs:"100%",sm:280}}}><MenuItem value="" disabled>Seleziona operatore</MenuItem>{operators.map(operator=><MenuItem key={operator.id} value={operator.id}>{operatorLabel(operator)}</MenuItem>)}</TextField><Button disabled={!selectedOperator} size="large" startIcon={<WidgetsOutlinedIcon/>} variant={mode==="package"?"contained":"outlined"} onClick={()=>chooseMode("package")}>Apri nuovo pacco</Button></Stack>{!selectedOperator?<Alert severity="warning" sx={{mb:1.5}}>Seleziona un operatore prima di procedere.</Alert>:<Alert severity="success" variant="outlined" sx={{mb:1.5,py:0}}>Operatore attivo: {operatorLabel(selectedOperator)} · {mode==="package"?"Modalità pacco":"Modalità pannello singolo"}</Alert>}<ScannerInput disabled={!selectedOperator} value={scannerValue} onValueChange={setScannerValue} onScan={submitScan}/>{result&&<Alert severity={result.severity} sx={{mt:1.5}}>{result.message}</Alert>}</Paper>
    <Paper sx={{p:2,mb:2}}><Typography variant="h6" sx={{mb:1}}>Pannelli previsti</Typography><Table size="small"><TableHead><TableRow>{["Stato","Pannello","Master Panel","Tipologia","Dimensioni","Peso","Situazione","Azioni"].map(h=><TableCell key={h} align={h==="Azioni"?"center":"left"}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{panels.map(panel=>{const closedPackage=isInPackage(panel),inOpenPackage=openPanels.some(open=>panelKey(open)===panelKey(panel)),singleAvailable=panel.preparato||singles.some(unit=>unit.commessa===target.commessa&&unit.camion===target.camion&&unit.numeroPannello===panel.numeroPannello);const situation=panel.caricato?"CARICATO":closedPackage||inOpenPackage?"IN PACCO":singleAvailable?"DISPONIBILE":"MANCANTE";const color=situation==="DISPONIBILE"?"success":situation==="IN PACCO"?"info":situation==="CARICATO"?"warning":"default",packageLabel=closedPackage?.codice??(inOpenPackage?"Pacco aperto":null);return <TableRow key={panelKey(panel)} sx={{bgcolor:situation==="DISPONIBILE"?"rgba(76,175,80,.08)":situation==="IN PACCO"?"rgba(33,150,243,.08)":situation==="CARICATO"?"rgba(255,152,0,.08)":undefined}}><TableCell><Chip size="small" color={color} variant={situation==="MANCANTE"?"outlined":"filled"} label={situation}/></TableCell><TableCell sx={{fontWeight:700}}>{panel.numeroPannello}</TableCell><TableCell>{panel.numeroMasterPanel}</TableCell><TableCell>{panel.tipoPannello||"—"}</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{Math.round(panel.spessore)} × {Math.round(panel.lunghezza)} × {Math.round(panel.altezza)} mm</TableCell><TableCell sx={{whiteSpace:"nowrap"}}>{panel.peso.toFixed(1)} kg</TableCell><TableCell>{packageLabel?`${situation} · ${packageLabel}`:situation}</TableCell><TableCell align="center">{situation==="DISPONIBILE"&&<IconButton size="small" disabled={!selectedOperator} title={selectedOperator?"Annulla scansione":"Seleziona un operatore"} onClick={()=>setUndoPanel(panel)}><UndoIcon fontSize="small"/></IconButton>}</TableCell></TableRow>;})}</TableBody></Table></Paper>
    {mode==="package"&&<Paper sx={{p:2,mb:2}}><Stack direction="row" sx={{justifyContent:"space-between",alignItems:"center"}}><Box><Typography variant="h6">Pacco aperto</Typography><Typography color="text.secondary">{openPanels.length} pannelli · {packageWeight(openPanels).toFixed(1)} kg · {packageVolume(openPanels).toFixed(3)} m³</Typography></Box><Button variant="contained" disabled={!openPanels.length} onClick={closePackage}>Chiudi pacco</Button></Stack><Table size="small" sx={{mt:1}}><TableHead><TableRow>{["Pannello","Master panel","Dimensioni","Peso","Volume",""].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{openPanels.map(p=><TableRow key={p.numeroPannello}><TableCell>{p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)} × {Math.round(p.lunghezza)} × {Math.round(p.altezza)}</TableCell><TableCell>{p.peso.toFixed(1)} kg</TableCell><TableCell>{p.volume.toFixed(3)} m³</TableCell><TableCell><IconButton color="error" onClick={()=>setRemovePanel(p)}><DeleteOutlinedIcon/></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper>}
    {closedPack&&<PackagePrintPreview pack={closedPack}/>}<Dialog open={pendingPackageCode!==null} onClose={()=>setPendingPackageCode(null)} fullWidth maxWidth="sm"><DialogTitle>Dimensioni esterne pacco</DialogTitle><DialogContent><Box sx={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:2,pt:1}}>{[["Codice pacco provvisorio",pendingPackageCode??""],["Commessa",target.commessa],["Cliente",target.cliente],["Camion",target.camion],["Numero pannelli",openPanels.length],["Peso totale",`${packageWeight(openPanels).toFixed(1)} kg`],["Volume totale pannelli",`${packageVolume(openPanels).toFixed(3)} m³`]].map(([label,value])=><Box key={label}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{value}</Typography></Box>)}</Box><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:2,mt:3}}><TextField autoFocus required type="number" label="Lunghezza pacco (mm)" value={packageLength} onChange={event=>setPackageLength(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/><TextField required type="number" label="Larghezza pacco (mm)" value={packageWidth} onChange={event=>setPackageWidth(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/><TextField required type="number" label="Altezza pacco (mm)" value={packageHeight} onChange={event=>setPackageHeight(event.target.value)} slotProps={{htmlInput:{min:1,step:"any"}}}/></Box></DialogContent><DialogActions><Button onClick={()=>setPendingPackageCode(null)}>Annulla</Button><Button variant="contained" disabled={!packageDimensionsValid} onClick={confirmPackageClose}>Conferma chiusura pacco</Button></DialogActions></Dialog><Dialog open={removePanel!==null} onClose={()=>setRemovePanel(null)}><DialogTitle>Rimuovi pannello</DialogTitle><DialogContent><DialogContentText>Vuoi rimuovere il pannello {removePanel?.numeroPannello} dal pacco aperto?</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setRemovePanel(null)}>Annulla</Button><Button color="error" onClick={()=>void confirmRemovePanel()}>Rimuovi</Button></DialogActions></Dialog>
    <Dialog open={undoPanel!==null} onClose={()=>setUndoPanel(null)}><DialogTitle>Annulla scansione</DialogTitle><DialogContent><DialogContentText>Riportare il pannello {undoPanel?.numeroPannello} allo stato MANCANTE?</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setUndoPanel(null)}>Annulla</Button><Button variant="contained" onClick={()=>void confirmUndoPanel()}>Conferma</Button></DialogActions></Dialog>
  </Box>;
}
