import { useRef, useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import { Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,IconButton,Paper,Snackbar,Switch,Tab,Table,TableBody,TableCell,TableHead,TableRow,Tabs,TextField,Typography } from "@mui/material";
import type { ImpostazioneOperativa,Operatore,Rimorchio,SettingsData,Trasportatore } from "../models/Settings";
import { createRegistryId,createSettingsBackup,parseSettingsBackup } from "../services/settingsStore";
import type { SettingsBackup } from "../services/settingsStore";

type Section="operatori"|"rimorchi"|"trasportatori"|"listeOperative";
type FormData=Record<string,string|boolean>;
type RecordItem=Operatore|Rimorchio|Trasportatore|ImpostazioneOperativa;
interface Props{settings:SettingsData;usedOperatorIds:Set<string>;loadErrors:string[];onChange:(settings:SettingsData)=>Promise<boolean>;onBack:()=>void}
const emptyForms:Record<Section,FormData>={operatori:{id:"",nome:"",cognome:"",sigla:"",attivo:true},rimorchi:{id:"",targa:"",descrizione:"",note:"",attivo:true},trasportatori:{id:"",nome:"",note:"",attivo:true},listeOperative:{chiave:"",valore:"",descrizione:"",attivo:true}};
const idOf=(record:RecordItem)=>"id" in record?record.id:record.chiave;

export default function Settings({settings,usedOperatorIds,loadErrors,onChange,onBack}:Props){
  const [section,setSection]=useState<Section>("operatori");
  const [form,setForm]=useState<FormData|null>(null);
  const [confirm,setConfirm]=useState<{action:"toggle"|"delete";id:string}|null>(null);
  const [pendingBackup,setPendingBackup]=useState<SettingsBackup|null>(null);
  const [notice,setNotice]=useState<{text:string;severity:"success"|"error"}|null>(null);
  const importRef=useRef<HTMLInputElement>(null);
  const records:RecordItem[]=settings[section];
  const save=()=>{if(!form)return;let next=settings;if(section==="operatori"){if(!form.nome||!form.cognome)return setNotice({text:"Nome e cognome sono obbligatori",severity:"error"});next={...settings,operatori:upsert(settings.operatori,{id:String(form.id||createRegistryId("OP")),nome:String(form.nome),cognome:String(form.cognome),sigla:String(form.sigla),attivo:Boolean(form.attivo)})};}else if(section==="rimorchi"){if(!form.targa)return setNotice({text:"La targa è obbligatoria",severity:"error"});next={...settings,rimorchi:upsert(settings.rimorchi,{id:String(form.id||createRegistryId("RIM")),targa:String(form.targa),descrizione:String(form.descrizione),note:String(form.note),attivo:Boolean(form.attivo)})};}else if(section==="trasportatori"){if(!form.nome)return setNotice({text:"Il nome è obbligatorio",severity:"error"});next={...settings,trasportatori:upsert(settings.trasportatori,{id:String(form.id||createRegistryId("TRA")),nome:String(form.nome),note:String(form.note),attivo:Boolean(form.attivo)})};}else{if(!form.chiave||!form.valore)return setNotice({text:"Chiave e valore sono obbligatori",severity:"error"});next={...settings,listeOperative:upsert(settings.listeOperative,{chiave:String(form.chiave),valore:String(form.valore),descrizione:String(form.descrizione),attivo:Boolean(form.attivo)})};}onChange(next);setForm(null);setNotice({text:"Anagrafica salvata",severity:"success"});};
  const applyConfirm=async()=>{if(!confirm)return;const record=records.find(item=>idOf(item)===confirm.id);if(!record)return;const label=section==="operatori"?"Operatore":section==="rimorchi"?"Rimorchio":section==="trasportatori"?"Trasportatore":"Valore operativo";if(confirm.action==="delete"&&section==="operatori"&&usedOperatorIds.has(confirm.id)){setNotice({text:"L'operatore è già utilizzato e non può essere eliminato.",severity:"error"});setConfirm(null);return;}const nextActive=confirm.action==="delete"?false:!record.attivo;const nextRecords=records.map(item=>idOf(item)===confirm.id?{...item,attivo:nextActive}:item);const saved=await onChange({...settings,[section]:nextRecords});setConfirm(null);setNotice(saved?{text:confirm.action==="delete"?`Eliminazione fisica non disponibile. ${label} disattivato.`:`${label} ${nextActive?"riattivato":"disattivato"}.`,severity:"success"}:{text:"Errore durante il salvataggio.",severity:"error"});};
  const exportBackup=()=>{const blob=new Blob([JSON.stringify(createSettingsBackup(settings),null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`loadmaster-anagrafiche-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setNotice({text:"Anagrafiche esportate",severity:"success"});};
  const selectBackup=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{setPendingBackup(parseSettingsBackup(await file.text()));}catch(error){setNotice({text:error instanceof Error?error.message:"Backup non valido",severity:"error"});}};
  const importBackup=()=>{if(!pendingBackup)return;onChange({...settings,operatori:pendingBackup.operatori,rimorchi:pendingBackup.rimorchi,trasportatori:pendingBackup.trasportatori});setPendingBackup(null);setNotice({text:"Anagrafiche importate",severity:"success"});};
  return <Box>
    <Box sx={{display:"flex",alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Impostazioni</Typography></Box>
    {loadErrors.map(message=><Alert key={message} severity="warning" sx={{mb:1}}>{message}</Alert>)}
    <Paper sx={{p:2}}><Tabs value={section} onChange={(_,value:Section)=>setSection(value)}><Tab value="operatori" label="Operatori"/><Tab value="rimorchi" label="Rimorchi Essepi"/><Tab value="trasportatori" label="Trasportatori"/><Tab value="listeOperative" label="Liste operative"/></Tabs>
      <input hidden ref={importRef} type="file" accept="application/json,.json" onChange={selectBackup}/><Box sx={{display:"flex",justifyContent:"flex-end",gap:1,my:2}}><Button onClick={exportBackup}>Esporta anagrafiche</Button><Button onClick={()=>importRef.current?.click()}>Importa anagrafiche</Button><Button variant="contained" onClick={()=>setForm({...emptyForms[section]})}>Aggiungi</Button></Box>
      <Table><TableHead><TableRow>{headers[section].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{records.map(record=><TableRow key={idOf(record)} sx={{opacity:record.attivo?1:.5}}>{cells(section,record).map((cell,index)=><TableCell key={`${idOf(record)}-${index}`}>{cell}</TableCell>)}<TableCell><Chip color={record.attivo?"success":"default"} label={record.attivo?"Attivo":"Disattivo"} size="small"/></TableCell><TableCell><IconButton onClick={()=>setForm({...record})}><EditOutlinedIcon/></IconButton><Button size="small" onClick={()=>setConfirm({action:"toggle",id:idOf(record)})}>{record.attivo?"Disattiva":"Riattiva"}</Button><IconButton color="error" onClick={()=>setConfirm({action:"delete",id:idOf(record)})}><DeleteOutlinedIcon/></IconButton></TableCell></TableRow>)}</TableBody></Table>
    </Paper>
    <Dialog open={form!==null} onClose={()=>setForm(null)} fullWidth maxWidth="sm"><DialogTitle>{form&&(section==="listeOperative"?form.chiave:form.id)?"Modifica":"Aggiungi"} {titles[section]}</DialogTitle><DialogContent><Box sx={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:2,pt:1}}>{fields[section].map(field=><TextField key={field.key} disabled={field.key==="chiave"&&Boolean(form?.chiave)} label={field.label} value={String(form?.[field.key]??"")} onChange={event=>setForm(current=>current?{...current,[field.key]:event.target.value}:current)}/>) }<FormControlLabel control={<Switch checked={Boolean(form?.attivo)} onChange={event=>setForm(current=>current?{...current,attivo:event.target.checked}:current)}/>} label="Attivo"/></Box></DialogContent><DialogActions><Button onClick={()=>setForm(null)}>Annulla</Button><Button variant="contained" onClick={save}>Salva</Button></DialogActions></Dialog>
    <Dialog open={confirm!==null} onClose={()=>setConfirm(null)}><DialogTitle>Conferma operazione</DialogTitle><DialogContent>{confirm?.action==="delete"?"Eliminare definitivamente il record?":"Confermare il cambio di stato?"}</DialogContent><DialogActions><Button onClick={()=>setConfirm(null)}>Annulla</Button><Button color={confirm?.action==="delete"?"error":"primary"} variant="contained" onClick={applyConfirm}>Conferma</Button></DialogActions></Dialog>
    <Dialog open={pendingBackup!==null} onClose={()=>setPendingBackup(null)}><DialogTitle>Importa anagrafiche</DialogTitle><DialogContent>Confermi la sostituzione delle anagrafiche correnti con {pendingBackup?.operatori.length??0} operatori, {pendingBackup?.rimorchi.length??0} rimorchi e {pendingBackup?.trasportatori.length??0} trasportatori?</DialogContent><DialogActions><Button onClick={()=>setPendingBackup(null)}>Annulla</Button><Button variant="contained" onClick={importBackup}>Conferma importazione</Button></DialogActions></Dialog>
    <Snackbar open={notice!==null} autoHideDuration={3500} onClose={()=>setNotice(null)}><Alert severity={notice?.severity??"success"}>{notice?.text}</Alert></Snackbar>
  </Box>;
}

function upsert<T extends {id:string}|{chiave:string}>(list:T[],record:T){const key="id" in record?record.id:record.chiave;return list.some(item=>("id" in item?item.id:item.chiave)===key)?list.map(item=>("id" in item?item.id:item.chiave)===key?record:item):[...list,record];}
const titles:Record<Section,string>={operatori:"operatore",rimorchi:"rimorchio",trasportatori:"trasportatore",listeOperative:"valore operativo"};
const headers:Record<Section,string[]>={operatori:["ID","Nome","Cognome","Sigla","Stato","Operazioni"],rimorchi:["ID","Targa","Descrizione","Note","Stato","Operazioni"],trasportatori:["ID","Nome","Note","Stato","Operazioni"],listeOperative:["Chiave","Valore","Descrizione","Stato","Operazioni"]};
const fields:Record<Section,{key:string;label:string}[]>={operatori:[{key:"nome",label:"Nome"},{key:"cognome",label:"Cognome"},{key:"sigla",label:"Sigla"}],rimorchi:[{key:"targa",label:"Targa rimorchio"},{key:"descrizione",label:"Descrizione"},{key:"note",label:"Note"}],trasportatori:[{key:"nome",label:"Ragione sociale / Nome"},{key:"note",label:"Note"}],listeOperative:[{key:"chiave",label:"Chiave"},{key:"valore",label:"Valore"},{key:"descrizione",label:"Descrizione"}]};
function cells(section:Section,record:RecordItem){if(section==="operatori"){const r=record as Operatore;return[r.id,r.nome,r.cognome,r.sigla]}if(section==="rimorchi"){const r=record as Rimorchio;return[r.id,r.targa,r.descrizione,r.note]}if(section==="trasportatori"){const r=record as Trasportatore;return[r.id,r.nome,r.note]}const r=record as ImpostazioneOperativa;return[r.chiave,r.valore,r.descrizione];}
