import { useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, Paper, Snackbar, Switch, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, TextField, Typography } from "@mui/material";
import type { ImpostazioneOperativa, Operatore, Rimorchio, SettingsData, Trasportatore } from "../models/Settings";
import { createRegistryId } from "../services/settingsStore";

type Section="operatori"|"rimorchi"|"trasportatori"|"listeOperative";
type FormData=Record<string,string|boolean>;
interface Props{settings:SettingsData;usedOperatorIds:Set<string>;onChange:(settings:SettingsData)=>void;onBack:()=>void;}
const emptyForms:Record<Section,FormData>={operatori:{id:"",nome:"",cognome:"",sigla:"",attivo:true},rimorchi:{id:"",targa:"",descrizione:"",note:"",attivo:true},trasportatori:{id:"",nome:"",note:"",attivo:true},listeOperative:{chiave:"",valore:"",descrizione:"",attivo:true}};

export default function Settings({settings,usedOperatorIds,onChange,onBack}:Props){
  const [section,setSection]=useState<Section>("operatori");const [form,setForm]=useState<FormData|null>(null);const [confirm,setConfirm]=useState<{action:"toggle"|"delete";id:string}|null>(null);const [notice,setNotice]=useState<{text:string;severity:"success"|"error"}|null>(null);
  const records=settings[section];const idOf=(record:Operatore|Rimorchio|Trasportatore|ImpostazioneOperativa)=>"id" in record?record.id:record.chiave;
  const edit=(record:Operatore|Rimorchio|Trasportatore|ImpostazioneOperativa)=>setForm({...record});
  const save=()=>{if(!form)return;let next:SettingsData={...settings};if(section==="operatori"){if(!form.nome||!form.cognome)return setNotice({text:"Nome e cognome sono obbligatori",severity:"error"});const record:Operatore={id:String(form.id||createRegistryId("OP")),nome:String(form.nome),cognome:String(form.cognome),sigla:String(form.sigla),attivo:Boolean(form.attivo)};next={...next,operatori:upsert(settings.operatori,record)}}else if(section==="rimorchi"){if(!form.targa)return setNotice({text:"La targa è obbligatoria",severity:"error"});const record:Rimorchio={id:String(form.id||createRegistryId("RIM")),targa:String(form.targa),descrizione:String(form.descrizione),note:String(form.note),attivo:Boolean(form.attivo)};next={...next,rimorchi:upsert(settings.rimorchi,record)}}else if(section==="trasportatori"){if(!form.nome)return setNotice({text:"Il nome è obbligatorio",severity:"error"});const record:Trasportatore={id:String(form.id||createRegistryId("TRA")),nome:String(form.nome),note:String(form.note),attivo:Boolean(form.attivo)};next={...next,trasportatori:upsert(settings.trasportatori,record)}}else{if(!form.chiave||!form.valore)return setNotice({text:"Chiave e valore sono obbligatori",severity:"error"});const record:ImpostazioneOperativa={chiave:String(form.chiave),valore:String(form.valore),descrizione:String(form.descrizione),attivo:Boolean(form.attivo)};next={...next,listeOperative:upsert(settings.listeOperative,record)}}onChange(next);setForm(null);setNotice({text:"Anagrafica salvata",severity:"success"});};
  const applyConfirm=()=>{if(!confirm)return;const list=settings[section];const record=list.find(item=>idOf(item)===confirm.id);if(!record)return;if(confirm.action==="delete"){if(section==="operatori"&&usedOperatorIds.has(confirm.id)){setNotice({text:"Operatore già utilizzato: disattivalo invece di eliminarlo",severity:"error"});setConfirm(null);return;}onChange({...settings,[section]:list.filter(item=>idOf(item)!==confirm.id)});}else onChange({...settings,[section]:list.map(item=>idOf(item)===confirm.id?{...item,attivo:!item.attivo}:item)});setConfirm(null);setNotice({text:confirm.action==="delete"?"Record eliminato":"Stato aggiornato",severity:"success"});};
  return <Box><Box sx={{display:"flex",alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Impostazioni</Typography></Box><Paper sx={{p:2}}><Tabs value={section} onChange={(_,value:Section)=>setSection(value)}><Tab value="operatori" label="Operatori"/><Tab value="rimorchi" label="Rimorchi Essepi"/><Tab value="trasportatori" label="Trasportatori"/><Tab value="listeOperative" label="Liste operative"/></Tabs><Box sx={{display:"flex",justifyContent:"flex-end",my:2}}><Button variant="contained" onClick={()=>setForm({...emptyForms[section]})}>Aggiungi</Button></Box><Table><TableHead><TableRow>{headers[section].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{records.map(record=><TableRow key={idOf(record)} sx={{opacity:record.attivo?1:.5}}>{cells(section,record).map((cell,index)=><TableCell key={index}>{cell}</TableCell>)}<TableCell><Chip color={record.attivo?"success":"default"} label={record.attivo?"Attivo":"Disattivo"} size="small"/></TableCell><TableCell><IconButton onClick={()=>edit(record)}><EditOutlinedIcon/></IconButton><Button size="small" onClick={()=>setConfirm({action:"toggle",id:idOf(record)})}>{record.attivo?"Disattiva":"Riattiva"}</Button><IconButton color="error" onClick={()=>setConfirm({action:"delete",id:idOf(record)})}><DeleteOutlinedIcon/></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Dialog open={form!==null} onClose={()=>setForm(null)} fullWidth maxWidth="sm"><DialogTitle>{form&&(section==="listeOperative"?form.chiave:form.id)?"Modifica":"Aggiungi"} {titles[section]}</DialogTitle><DialogContent><Box sx={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:2,pt:1}}>{fields[section].map(field=><TextField key={field.key} disabled={field.key==="chiave"&&Boolean(form?.chiave)} label={field.label} value={String(form?.[field.key]??"")} onChange={e=>setForm(current=>current?{...current,[field.key]:e.target.value}:current)} />)}<FormControlLabel control={<Switch checked={Boolean(form?.attivo)} onChange={e=>setForm(current=>current?{...current,attivo:e.target.checked}:current)}/>} label="Attivo"/></Box></DialogContent><DialogActions><Button onClick={()=>setForm(null)}>Annulla</Button><Button variant="contained" onClick={save}>Salva</Button></DialogActions></Dialog>
    <Dialog open={confirm!==null} onClose={()=>setConfirm(null)}><DialogTitle>Conferma operazione</DialogTitle><DialogContent>{confirm?.action==="delete"?"Eliminare definitivamente il record?":"Confermare il cambio di stato?"}</DialogContent><DialogActions><Button onClick={()=>setConfirm(null)}>Annulla</Button><Button color={confirm?.action==="delete"?"error":"primary"} variant="contained" onClick={applyConfirm}>Conferma</Button></DialogActions></Dialog><Snackbar open={notice!==null} autoHideDuration={3500} onClose={()=>setNotice(null)}><Alert severity={notice?.severity??"success"}>{notice?.text}</Alert></Snackbar>
  </Box>;
}

function upsert<T extends {id:string}|{chiave:string}>(list:T[],record:T){const key="id" in record?record.id:record.chiave;const index=list.findIndex(item=>("id" in item?item.id:item.chiave)===key);return index<0?[...list,record]:list.map((item,i)=>i===index?record:item);}
const titles:Record<Section,string>={operatori:"operatore",rimorchi:"rimorchio",trasportatori:"trasportatore",listeOperative:"valore operativo"};
const headers:Record<Section,string[]>={operatori:["ID","Nome","Cognome","Sigla","Stato","Operazioni"],rimorchi:["ID","Targa","Descrizione","Note","Stato","Operazioni"],trasportatori:["ID","Nome","Note","Stato","Operazioni"],listeOperative:["Chiave","Valore","Descrizione","Stato","Operazioni"]};
const fields:Record<Section,{key:string;label:string}[]>={operatori:[{key:"nome",label:"Nome"},{key:"cognome",label:"Cognome"},{key:"sigla",label:"Sigla"}],rimorchi:[{key:"targa",label:"Targa rimorchio"},{key:"descrizione",label:"Descrizione"},{key:"note",label:"Note"}],trasportatori:[{key:"nome",label:"Ragione sociale / Nome"},{key:"note",label:"Note"}],listeOperative:[{key:"chiave",label:"Chiave"},{key:"valore",label:"Valore"},{key:"descrizione",label:"Descrizione"}]};
function cells(section:Section,record:Operatore|Rimorchio|Trasportatore|ImpostazioneOperativa){if(section==="operatori"){const r=record as Operatore;return[r.id,r.nome,r.cognome,r.sigla]}if(section==="rimorchi"){const r=record as Rimorchio;return[r.id,r.targa,r.descrizione,r.note]}if(section==="trasportatori"){const r=record as Trasportatore;return[r.id,r.nome,r.note]}const r=record as ImpostazioneOperativa;return[r.chiave,r.valore,r.descrizione];}
