import { useEffect, useMemo, useRef, useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import UndoIcon from "@mui/icons-material/Undo";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, IconButton, LinearProgress, MenuItem, Paper, Snackbar, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import ScannerInput from "../components/scanning/ScannerInput";
import type { CaricoCamion, ScansioneCarico, TipoUnitaCarico } from "../models/Loading";
import type { Camion } from "../models/Camion";
import type { Pacco, UnitaSingola } from "../models/Scanning";
import type { Operatore, Rimorchio, Trasportatore } from "../models/Settings";
import { operatorLabel } from "../models/Settings";
import type { Commessa, Pannello } from "../types/excel";
import { packageQrText, panelQrText, parsePackageQr, parsePanelQr } from "../utils/panelQr";
import { completeLoadingApi, createLoadingSession, loadUnitApi, shipLoadingApi, unloadUnitApi, updateLoadingSession } from "../services/loadingApi";

interface Unit{backendId?:string;tipo:TipoUnitaCarico;codice:string;pannelli:Pannello[];peso:number;volume:number;stato:"DISPONIBILE"|"CARICATO"|"SPEDITO";}
const unitKey=(unit:Unit)=>`${unit.tipo}:${unit.codice}`;
interface Props{rows:Camion[];commesse:Commessa[];singles:UnitaSingola[];packages:Pacco[];operators:Operatore[];trailers:Rimorchio[];carriers:Trasportatore[];loads:CaricoCamion[];initialLoad?:CaricoCamion|null;onBack:()=>void;onResumeLoad:(loadId:string)=>void;onSessionChange:(load:CaricoCamion)=>void;onScanUnit:(row:Camion,unit:Unit)=>void;onUndoUnit:(row:Camion,unit:Unit)=>void;onComplete:(load:CaricoCamion,units:Unit[],destination:"trailer"|"carrier")=>void;}

export default function TruckLoading({rows,commesse,singles,packages,operators,trailers,carriers,loads,initialLoad,onBack,onResumeLoad,onSessionChange,onScanUnit,onUndoUnit,onComplete}:Props){
  operators=operators.filter(item=>item.attivo);trailers=trailers.filter(item=>item.attivo);carriers=carriers.filter(item=>item.attivo);
  const sessionChangeRef=useRef(onSessionChange);sessionChangeRef.current=onSessionChange;
  const loadsRef=useRef(loads);loadsRef.current=loads;
  const sessionIdRef=useRef(initialLoad?.loadId??crypto.randomUUID());
  const initialRow=initialLoad?rows.find(row=>row.commessa===initialLoad.commessa&&row.camion===initialLoad.camion)??null:null;
  const initialDestination=initialLoad?.tipoDestinazione==="RIMORCHIO_ESSEPI"?"trailer":initialLoad?.tipoDestinazione==="TRASPORTATORE"?"carrier":initialLoad?.rimorchioId?"trailer":initialLoad?.trasportatoreId?"carrier":"";
  const [selected,setSelected]=useState<Camion|null>(initialRow);const [persistedSessionId,setPersistedSessionId]=useState(initialLoad?.loadId??"");const [persistedUnitIds,setPersistedUnitIds]=useState<Map<string,string>>(new Map(initialLoad?.scansioni.flatMap(scan=>scan.unitId?[[`${scan.tipoUnita}:${scan.codiceUnita}`,scan.unitId] as const]:[])??[]));const [operatorId,setOperatorId]=useState(initialLoad?.operatoreId??"");const [destination,setDestination]=useState<"trailer"|"carrier"|"">(initialDestination);const [destinationId,setDestinationId]=useState(initialLoad?.rimorchioId??initialLoad?.trasportatoreId??"");const [scanner,setScanner]=useState("");const [testUnitKey,setTestUnitKey]=useState("");const [startedAt,setStartedAt]=useState(initialLoad?.avviatoIl??"");const [expanded,setExpanded]=useState<Set<string>>(new Set());const [undoUnit,setUndoUnit]=useState<Unit|null>(null);const [confirmClose,setConfirmClose]=useState(false);const [notice,setNotice]=useState<{severity:"success"|"error";text:string}|null>(null);
  const displayRows=rows.filter(row=>!loads.some(load=>load.commessa===row.commessa&&load.camion===row.camion&&load.stato==="SPEDITO")).map(row=>loads.some(load=>load.commessa===row.commessa&&load.camion===row.camion&&load.stato==="IN_CARICO")?{...row,stato:"In carico" as const}:row);const selectable=displayRows.filter(row=>row.stato==="Da caricare"||row.stato==="In carico").sort((a,b)=>a.stato==="In carico"&&b.stato!=="In carico"?-1:a.stato!=="In carico"&&b.stato==="In carico"?1:a.commessa.localeCompare(b.commessa));const commessa=selected?commesse.find(item=>item.ordine===selected.commessa):undefined;
  const units=useMemo<Unit[]>(()=>{if(!selected||!commessa)return[];const relevantPackages=packages.filter(pack=>pack.commessa===selected.commessa&&pack.camion===selected.camion);const childNumbers=new Set(relevantPackages.flatMap(pack=>pack.pannelli.map(panel=>panel.numeroPannello)));const singleUnits=singles.flatMap(unit=>{if(unit.commessa!==selected.commessa||unit.camion!==selected.camion||childNumbers.has(unit.numeroPannello))return[];const panel=commessa.pannelli.find(item=>item.numeroCamion===selected.camion&&item.numeroPannello===unit.numeroPannello);return panel?[{tipo:"SINGOLO" as const,codice:panel.numeroPannello,pannelli:[panel],peso:panel.peso,volume:panel.volume,stato:panel.spedito?"SPEDITO" as const:panel.caricato?"CARICATO" as const:"DISPONIBILE" as const}]:[];});const packageUnits=relevantPackages.map(pack=>({tipo:"PACCO" as const,codice:pack.codice,pannelli:pack.pannelli,peso:pack.pesoTotale,volume:pack.volumeTotale,stato:pack.stato==="SPEDITO"?"SPEDITO" as const:pack.stato==="CARICATO"?"CARICATO" as const:"DISPONIBILE" as const}));return[...singleUnits,...packageUnits];},[selected,commessa,singles,packages]);
  const loaded=useMemo(()=>new Set(units.filter(unit=>unit.stato==="CARICATO"||unit.stato==="SPEDITO").map(unitKey)),[units]);
  const operator=operators.find(item=>item.id===operatorId);const destinationValid=destination==="trailer"?trailers.some(item=>item.id===destinationId):destination==="carrier"?carriers.some(item=>item.id===destinationId):false;const ready=Boolean(operator&&destinationValid);const loadedUnits=units.filter(unit=>loaded.has(`${unit.tipo}:${unit.codice}`));const loadedPanels=loadedUnits.reduce((total,unit)=>total+unit.pannelli.length,0);const loadedWeight=loadedUnits.reduce((total,unit)=>total+unit.peso,0);const loadedVolume=loadedUnits.reduce((total,unit)=>total+unit.volume,0);const complete=units.length>0&&loaded.size===units.length;const percent=units.length?loaded.size/units.length*100:0;
  useEffect(()=>{if(!selected||!operator||!destination||!destinationValid)return;const input={operatorId:operator.id,destinationType:destination==="trailer"?"RIMORCHIO_ESSEPI" as const:"TRASPORTATORE" as const,...(destination==="trailer"?{trailerId:destinationId}:{carrierId:destinationId})};void (persistedSessionId?updateLoadingSession(persistedSessionId,input):createLoadingSession(selected.id,input)).then(session=>{setPersistedSessionId(session.id);sessionIdRef.current=session.id;setStartedAt(session.startedAt);setPersistedUnitIds(new Map(session.units.map(unit=>[`${unit.unitType==="PANEL"?"SINGOLO":"PACCO"}:${unit.code}`,unit.id])));}).catch(()=>setNotice({severity:"error",text:"Impossibile salvare la sessione di carico"}));},[selected,operator,destination,destinationId,destinationValid,persistedSessionId]);
  const start=(row:Camion)=>{const existing=loads.find(load=>load.commessa===row.commessa&&load.camion===row.camion&&load.stato==="IN_CARICO");if(existing){onResumeLoad(existing.loadId);return;}setSelected(row);setOperatorId("");setDestination("");setDestinationId("");setStartedAt(new Date().toISOString());};
  const submit=async(raw:string)=>{setScanner("");if(!selected||!ready||!operator||!persistedSessionId){setNotice({severity:"error",text:"Attendi il salvataggio di operatore e destinazione"});return;}let unit:Unit|undefined;if(raw.trim().startsWith("PK=")){const qr=parsePackageQr(raw);if(!qr)return setNotice({severity:"error",text:"QR non valido"});if(qr.commessa!==selected.commessa)return setNotice({severity:"error",text:"Commessa errata"});if(qr.camion!==selected.camion)return setNotice({severity:"error",text:"Camion errato"});unit=units.find(item=>item.tipo==="PACCO"&&item.codice===qr.codicePacco);if(!unit)return setNotice({severity:"error",text:"Unità non prevista"});if(unit.stato!=="DISPONIBILE")return setNotice({severity:"error",text:unit.stato==="SPEDITO"?"Unità già spedita":"Pacco non disponibile"});}else{const qr=parsePanelQr(raw);if(!qr)return setNotice({severity:"error",text:"QR non valido"});if(qr.commessa!==selected.commessa)return setNotice({severity:"error",text:"Commessa errata"});if(qr.camion!==selected.camion)return setNotice({severity:"error",text:"Camion errato"});const parent=units.find(item=>item.tipo==="PACCO"&&item.pannelli.some(panel=>panel.numeroPannello===qr.numeroPannello));if(parent)return setNotice({severity:"error",text:`Pannello appartenente al pacco ${parent.codice}`});unit=units.find(item=>item.tipo==="SINGOLO"&&item.codice===qr.numeroPannello);if(!unit)return setNotice({severity:"error",text:"Unità non prevista"});if(unit.stato!=="DISPONIBILE")return setNotice({severity:"error",text:unit.stato==="SPEDITO"?"Unità già spedita":"Unità già caricata"});}if(loaded.has(unitKey(unit)))return setNotice({severity:"error",text:"Unità già caricata"});const panelId=unit.tipo==="SINGOLO"?unit.pannelli[0]?.backendId:undefined,packageId=unit.tipo==="PACCO"?packages.find(pack=>pack.codice===unit!.codice)?.id:undefined;try{const session=await loadUnitApi(persistedSessionId,{unitType:unit.tipo==="SINGOLO"?"PANEL":"PACKAGE",...(panelId?{panelId}:{}),...(packageId?{packageId}:{}),operatorId:operator.id});setPersistedUnitIds(new Map(session.units.map(item=>[`${item.unitType==="PANEL"?"SINGOLO":"PACCO"}:${item.code}`,item.id])));onScanUnit(selected,unit);setNotice({severity:"success",text:`${unit.tipo} ${unit.codice} caricato`});}catch{setNotice({severity:"error",text:"Unità non disponibile o già caricata"});}};
  const undo=async()=>{if(!selected||!undoUnit||!operator||!persistedSessionId)return;const id=persistedUnitIds.get(unitKey(undoUnit));if(!id)return;try{const session=await unloadUnitApi(persistedSessionId,id,operator.id);setPersistedUnitIds(new Map(session.units.map(item=>[`${item.unitType==="PANEL"?"SINGOLO":"PACCO"}:${item.code}`,item.id])));onUndoUnit(selected,undoUnit);setUndoUnit(null);setNotice({severity:"success",text:"Scansione annullata"});}catch{setNotice({severity:"error",text:"Impossibile annullare la scansione"});}};
  const close=async()=>{if(!selected||!operator||!destination||!destinationValid||!complete||!persistedSessionId)return;try{if(destination==="trailer")await completeLoadingApi(persistedSessionId);else await shipLoadingApi(persistedSessionId,destinationId);const now=new Date().toISOString();const scansioni:ScansioneCarico[]=loadedUnits.map(unit=>({unitId:persistedUnitIds.get(unitKey(unit)),tipoUnita:unit.tipo,codiceUnita:unit.codice,commessa:selected.commessa,camion:selected.camion,operatoreId:operator.id,operatore:operatorLabel(operator),dataOra:now,peso:unit.peso,volume:unit.volume,esito:"OK"}));const load:CaricoCamion={loadId:persistedSessionId,backendLoadId:selected.id,commessa:selected.commessa,cliente:selected.cliente,camion:selected.camion,stato:destination==="trailer"?"ATTESA_SPEDIZIONE":"SPEDITO",rimorchioId:destination==="trailer"?destinationId:undefined,trasportatoreId:destination==="carrier"?destinationId:undefined,operatoreId:operator.id,operatore:operatorLabel(operator),avviatoIl:startedAt,completatoIl:now,...(destination==="carrier"?{speditoIl:now}:{}),scansioni,eventi:initialLoad?.eventi??[]};onComplete(load,loadedUnits,destination);setConfirmClose(false);setSelected(null);setNotice({severity:"success",text:destination==="trailer"?"Carico chiuso: attesa spedizione":"Partenza confermata"});}catch{setNotice({severity:"error",text:"Impossibile chiudere il carico"});}};
  const testUnit=units.find(unit=>unitKey(unit)===testUnitKey);const loadedTestUnit=units.find(unit=>loaded.has(unitKey(unit)));const packageTestUnit=units.find(unit=>unit.tipo==="PACCO");const unavailablePackage=units.find(unit=>unit.tipo==="PACCO"&&(unit.stato!=="DISPONIBILE"||loaded.has(unitKey(unit))));
  const qrForUnit=(unit:Unit,order=selected?.commessa??"",truck=selected?.camion??"")=>{if(selected&&order===`${selected.camion}-TEST`){truck=order;order=selected.commessa;}return unit.tipo==="PACCO"?packageQrText(unit.codice,order,selected?.cliente??"",truck,unit.pannelli.length,unit.peso,unit.volume):panelQrText({commessa:order,cliente:selected?.cliente??"",numeroPannello:unit.codice,camion:truck,spessore:unit.pannelli[0].spessore,lunghezza:unit.pannelli[0].lunghezza,altezza:unit.pannelli[0].altezza,peso:unit.peso});};
  useEffect(()=>{if(!selected||!startedAt)return;const existing=loadsRef.current.find(load=>load.loadId===sessionIdRef.current)??initialLoad;sessionChangeRef.current({loadId:sessionIdRef.current,commessa:selected.commessa,cliente:selected.cliente,camion:selected.camion,stato:"IN_CARICO",tipoDestinazione:destination==="trailer"?"RIMORCHIO_ESSEPI":destination==="carrier"?"TRASPORTATORE":undefined,rimorchioId:destination==="trailer"&&destinationId?destinationId:undefined,trasportatoreId:destination==="carrier"&&destinationId?destinationId:undefined,operatoreId:operatorId,operatore:operator?operatorLabel(operator):"",avviatoIl:startedAt,completatoIl:existing?.completatoIl,scansioni:existing?.scansioni??[],eventi:existing?.eventi??[]});},[selected,startedAt,operatorId,operator,destination,destinationId,initialLoad]);
  useEffect(()=>{if(initialLoad?.stato==="IN_CARICO"&&(!initialLoad.operatoreId||(!initialLoad.tipoDestinazione&&!initialLoad.rimorchioId&&!initialLoad.trasportatoreId)))setNotice({severity:"error",text:"Sessione precedente incompleta: selezionare operatore e destinazione."});},[initialLoad]);
  useEffect(()=>{if(!selected||!operator||!destination||!destinationValid||!startedAt)return;const existing=loads.find(load=>load.loadId===sessionIdRef.current)??initialLoad;const previousScans=existing?.scansioni??[];const scansioni=units.filter(unit=>loaded.has(unitKey(unit))).map(unit=>previousScans.find(scan=>scan.tipoUnita===unit.tipo&&scan.codiceUnita===unit.codice)??{tipoUnita:unit.tipo,codiceUnita:unit.codice,commessa:selected.commessa,camion:selected.camion,operatoreId:operator.id,operatore:operatorLabel(operator),dataOra:new Date().toISOString(),peso:unit.peso,volume:unit.volume,esito:"OK" as const});const previousKeys=new Set(previousScans.map(scan=>`${scan.tipoUnita}:${scan.codiceUnita}`));const currentKeys=new Set(scansioni.map(scan=>`${scan.tipoUnita}:${scan.codiceUnita}`));const added=scansioni.filter(scan=>!previousKeys.has(`${scan.tipoUnita}:${scan.codiceUnita}`)).map(scan=>({tipo:"UNITA_AGGIUNTA" as const,dataOra:scan.dataOra,operatoreId:operator.id,operatore:operatorLabel(operator)}));const removed=previousScans.filter(scan=>!currentKeys.has(`${scan.tipoUnita}:${scan.codiceUnita}`)).map(()=>({tipo:"UNITA_RIMOSSA" as const,dataOra:new Date().toISOString(),operatoreId:operator.id,operatore:operatorLabel(operator)}));sessionChangeRef.current({loadId:sessionIdRef.current,commessa:selected.commessa,cliente:selected.cliente,camion:selected.camion,stato:"IN_CARICO",rimorchioId:destination==="trailer"?destinationId:undefined,trasportatoreId:destination==="carrier"?destinationId:undefined,operatoreId:operator.id,operatore:operatorLabel(operator),avviatoIl:startedAt,completatoIl:existing?.completatoIl,scansioni,eventi:[...(existing?.eventi??[{tipo:"AVVIO" as const,dataOra:startedAt,operatoreId:operator.id,operatore:operatorLabel(operator)}]),...added,...removed]});},[loaded,operatorId,destination,destinationId,startedAt]);
  if(!selected)return <Box><Stack direction="row" sx={{alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Carico camion</Typography></Stack><Paper sx={{p:2}}><Typography variant="h6" sx={{mb:1}}>Carichi da caricare o completare</Typography><Table><TableHead><TableRow>{["Commessa","Cliente","Camion","Previsti","Disponibili","Caricati","Mancanti","Peso","Volume","Stato","Operazione"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{selectable.map(row=>{const inProgress=row.stato==="In carico";return <TableRow key={row.id}><TableCell>{row.commessa}</TableCell><TableCell>{row.cliente}</TableCell><TableCell>{row.camion}</TableCell><TableCell>{row.previsti}</TableCell><TableCell>{row.pronti}</TableCell><TableCell>{row.caricati}</TableCell><TableCell>{row.previsti-row.caricati}</TableCell><TableCell>{row.peso.toFixed(1)} kg</TableCell><TableCell>{row.volume.toFixed(3)} m³</TableCell><TableCell><Chip label={inProgress?"IN_CARICO":"DA_CARICARE"} color={inProgress?"warning":"info"} variant="outlined"/></TableCell><TableCell><Button variant="contained" onClick={()=>start(row)}>{inProgress?"Continua carico":"Avvia carico"}</Button></TableCell></TableRow>})}</TableBody></Table>{!selectable.length&&<Typography color="text.secondary" sx={{py:4,textAlign:"center"}}>Nessun carico disponibile</Typography>}</Paper></Box>;
  return <Box><Stack direction="row" sx={{alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={()=>setSelected(null)}>Carichi</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Carico {selected.commessa} · {selected.camion}</Typography></Stack>{initialLoad&&<Alert severity="info" sx={{mb:2}}><b>Carico riaperto - modifiche in corso</b><br/>Chiusura precedente: {initialLoad.completatoIl?new Date(initialLoad.completatoIl).toLocaleString("it-IT"):"—"} · Operatore riapertura: {initialLoad.operatore}</Alert>}<Paper sx={{p:2,mb:2}}><Box sx={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:1.5}}><TextField select required label="Operatore" value={operatorId} onChange={event=>setOperatorId(event.target.value)}><MenuItem value="" disabled>Seleziona operatore</MenuItem>{operators.map(item=><MenuItem key={item.id} value={item.id}>{operatorLabel(item)}</MenuItem>)}</TextField><TextField select required label="Destinazione" value={destination} onChange={event=>{setDestination(event.target.value as "trailer"|"carrier");setDestinationId("");}}><MenuItem value="trailer">Carico su rimorchio Essepi</MenuItem><MenuItem value="carrier">Ritiro diretto / Trasportatore</MenuItem></TextField><TextField select required disabled={!destination} label={destination==="trailer"?"Rimorchio Essepi":"Trasportatore"} value={destinationId} onChange={event=>setDestinationId(event.target.value)}>{(destination==="trailer"?trailers:carriers).map(item=><MenuItem key={item.id} value={item.id}>{"targa" in item?`${item.targa} — ${item.descrizione}`:item.nome}</MenuItem>)}</TextField></Box>{!ready&&<Alert severity="warning" sx={{mt:1.5}}>Seleziona operatore e destinazione prima di iniziare.</Alert>}</Paper>
    <Box sx={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:1,mb:2}}>{[["Unità caricate",loaded.size],["Unità mancanti",units.length-loaded.size],["Pannelli caricati",loadedPanels],["Peso caricato",`${loadedWeight.toFixed(1)} kg`],["Volume caricato",`${loadedVolume.toFixed(3)} m³`],["Avanzamento",`${percent.toFixed(0)}%`]].map(([label,value])=><Paper key={label} sx={{p:1.5,textAlign:"center"}}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" sx={{fontWeight:800}}>{value}</Typography></Paper>)}</Box><LinearProgress variant="determinate" value={percent} sx={{height:12,borderRadius:2,mb:2}}/><Paper sx={{p:2,mb:2}}><ScannerInput disabled={!ready} value={scanner} onValueChange={setScanner} onScan={submit}/></Paper>
    {import.meta.env.DEV&&<Paper variant="outlined" sx={{p:2,mb:2,borderColor:"warning.dark",bgcolor:"rgba(255,152,0,.05)"}}><Typography variant="h6" sx={{mb:1}}>Modalità test</Typography><Stack direction={{xs:"column",lg:"row"}} sx={{gap:1,alignItems:{lg:"center"},flexWrap:"wrap"}}><TextField select size="small" label="Unità da simulare" value={testUnitKey} onChange={event=>setTestUnitKey(event.target.value)} sx={{minWidth:300}}>{units.map(unit=><MenuItem key={unitKey(unit)} value={unitKey(unit)}>{unit.tipo} — {unit.codice} — {unit.peso.toFixed(1)} kg — {loaded.has(unitKey(unit))?"CARICATO":unit.stato}</MenuItem>)}</TextField><Button variant="contained" disabled={!ready||!testUnit} onClick={()=>testUnit&&submit(qrForUnit(testUnit))}>Simula scansione</Button><Button color="error" variant="outlined" disabled={!ready} onClick={()=>submit("QR_NON_VALIDO_TEST")}>QR non valido</Button><Button variant="outlined" disabled={!ready||!loadedTestUnit} onClick={()=>loadedTestUnit&&submit(qrForUnit(loadedTestUnit))}>Unità duplicata</Button><Button variant="outlined" disabled={!ready||!testUnit} onClick={()=>testUnit&&submit(qrForUnit(testUnit,"COMMESSA-TEST"))}>Altra commessa</Button><Button variant="outlined" disabled={!ready||!testUnit} onClick={()=>testUnit&&submit(qrForUnit(testUnit,selected.camion+"-TEST"))}>Altro camion</Button><Button variant="outlined" disabled={!ready||!packageTestUnit} onClick={()=>packageTestUnit&&submit(panelQrText({commessa:selected.commessa,cliente:selected.cliente,numeroPannello:packageTestUnit.pannelli[0].numeroPannello,camion:selected.camion,spessore:packageTestUnit.pannelli[0].spessore,lunghezza:packageTestUnit.pannelli[0].lunghezza,altezza:packageTestUnit.pannelli[0].altezza,peso:packageTestUnit.pannelli[0].peso}))}>Pannello di un pacco</Button><Button variant="outlined" disabled={!ready||!unavailablePackage} onClick={()=>unavailablePackage&&submit(qrForUnit(unavailablePackage))}>Pacco non disponibile</Button><Button variant="outlined" disabled={!ready||!loadedTestUnit} onClick={()=>loadedTestUnit&&submit(qrForUnit(loadedTestUnit))}>Unità già caricata</Button></Stack></Paper>}
    <Paper sx={{p:2}}><Table size="small"><TableHead><TableRow>{["","Tipo","Codice unità","Pannelli","Peso","Volume","Stato",""].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{units.flatMap(unit=>{const key=`${unit.tipo}:${unit.codice}`,isLoaded=loaded.has(key),isExpanded=expanded.has(unit.codice);const parent=<TableRow key={key} sx={{bgcolor:isLoaded?"rgba(76,175,80,.12)":undefined}}><TableCell>{isLoaded?<CheckCircleIcon color="success"/>:unit.tipo==="PACCO"?<IconButton onClick={()=>setExpanded(current=>{const next=new Set(current);next.has(unit.codice)?next.delete(unit.codice):next.add(unit.codice);return next;})}>{isExpanded?<ExpandLessIcon/>:<ExpandMoreIcon/>}</IconButton>:null}</TableCell><TableCell>{unit.tipo}</TableCell><TableCell>{unit.codice}</TableCell><TableCell>{unit.pannelli.length}</TableCell><TableCell>{unit.peso.toFixed(1)} kg</TableCell><TableCell>{unit.volume.toFixed(3)} m³</TableCell><TableCell>{isLoaded?"CARICATO":unit.stato}</TableCell><TableCell>{isLoaded&&<IconButton onClick={()=>setUndoUnit(unit)}><UndoIcon/></IconButton>}</TableCell></TableRow>;const children=unit.tipo==="PACCO"&&isExpanded?unit.pannelli.map(panel=><TableRow key={`${key}-${panel.numeroPannello}`}><TableCell/><TableCell sx={{pl:4}}>↳ Pannello</TableCell><TableCell>{panel.numeroPannello}</TableCell><TableCell>MP {panel.numeroMasterPanel}</TableCell><TableCell>{panel.peso.toFixed(1)} kg</TableCell><TableCell>{panel.volume.toFixed(3)} m³</TableCell><TableCell colSpan={2}/></TableRow>):[];return[parent,...children];})}</TableBody></Table><Stack direction="row" sx={{justifyContent:"flex-end",alignItems:"center",gap:2,mt:2}}>{!complete&&<Typography color="warning.main">Mancano {units.length-loaded.size} unità</Typography>}<Button size="large" variant="contained" disabled={!complete||!ready} onClick={()=>setConfirmClose(true)}>{destination==="carrier"?"Conferma partenza":"Chiudi carico su rimorchio"}</Button></Stack></Paper>
    <Dialog open={undoUnit!==null} onClose={()=>setUndoUnit(null)}><DialogTitle>Annulla scansione</DialogTitle><DialogContent><DialogContentText>Riportare {undoUnit?.tipo} {undoUnit?.codice} a DISPONIBILE?</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setUndoUnit(null)}>Annulla</Button><Button onClick={undo}>Conferma</Button></DialogActions></Dialog><Dialog open={confirmClose} onClose={()=>setConfirmClose(false)}><DialogTitle>Conferma chiusura carico</DialogTitle><DialogContent><DialogContentText>{destination==="carrier"?"Confermare la partenza del camion?":"Chiudere il carico sul rimorchio selezionato?"}</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setConfirmClose(false)}>Annulla</Button><Button variant="contained" onClick={close}>Conferma</Button></DialogActions></Dialog><Snackbar open={notice!==null} autoHideDuration={3500} onClose={()=>setNotice(null)}><Alert severity={notice?.severity??"success"}>{notice?.text}</Alert></Snackbar>
  </Box>;
}
