import { useState } from "react";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import DeleteOutlinedIcon from "@mui/icons-material/DeleteOutlined";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import PrintOutlinedIcon from "@mui/icons-material/PrintOutlined";
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, IconButton, MenuItem, Paper, Snackbar, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import type { Pacco, UnitaSingola } from "../models/Scanning";
import type { Commessa, Pannello } from "../types/excel";
import PackagePrintPreview from "../components/scanning/PackagePrintPreview";

interface Props { commesse:Commessa[]; singles:UnitaSingola[]; packages:Pacco[]; drafts:Map<string,Pannello[]>; onBack:()=>void; onCancelSingle:(unit:UnitaSingola)=>void; onCancelPackage:(pack:Pacco)=>void; onRemoveDraftPanel:(key:string,panel:Pannello)=>void; }
type Pending={kind:"single";unit:UnitaSingola;blocked:boolean}|{kind:"package";pack:Pacco;blocked:boolean}|{kind:"draft";key:string;panel:Pannello};
const draftParts=(key:string)=>key.split("\u0000");
export default function Warehouse({commesse,singles,packages,drafts,onBack,onCancelSingle,onCancelPackage,onRemoveDraftPanel}:Props){
  const [search,setSearch]=useState("");const [order,setOrder]=useState("");const [client,setClient]=useState("");const [truck,setTruck]=useState("");const [type,setType]=useState("all");const [pending,setPending]=useState<Pending|null>(null);const [printPack,setPrintPack]=useState<Pacco|null>(null);const [notice,setNotice]=useState<{message:string;severity:"success"|"error"}|null>(null);
  const panelFor=(unit:UnitaSingola)=>commesse.find(c=>c.ordine===unit.commessa)?.pannelli.find(p=>p.numeroCamion===unit.camion&&p.numeroPannello===unit.numeroPannello);
  const clientFor=(unit:UnitaSingola)=>commesse.find(c=>c.ordine===unit.commessa)?.cliente??"";
  const match=(values:string[],kind:"single"|"package")=>{const text=values.join(" ").toLowerCase();return(!search||text.includes(search.toLowerCase()))&&(!order||values.includes(order))&&(!client||values.includes(client))&&(!truck||values.includes(truck))&&(type==="all"||type===kind);};
  const visibleSingles=singles.filter(unit=>{const p=panelFor(unit);return p&&match([unit.commessa,clientFor(unit),unit.camion,unit.numeroPannello],"single");});
  const visiblePackages=packages.filter(pack=>match([pack.codice,pack.commessa,pack.cliente,pack.camion],"package"));
  const confirm=()=>{if(!pending)return;if(pending.kind==="single"){onCancelSingle(pending.unit);setNotice({message:"Scansione del pannello annullata",severity:"success"});}else if(pending.kind==="package"){onCancelPackage(pending.pack);setNotice({message:"Pacco annullato e pannelli riportati a MANCANTE",severity:"success"});}else{onRemoveDraftPanel(pending.key,pending.panel);setNotice({message:"Pannello rimosso dal pacco aperto",severity:"success"});}setPending(null);};
  const options=(selector:(c:Commessa)=>string)=>Array.from(new Set(commesse.map(selector).filter(Boolean)));
  return <Box><Stack direction="row" sx={{alignItems:"center",mb:2}}><Button startIcon={<ArrowBackIcon/>} onClick={onBack}>Dashboard</Button><Typography variant="h4" sx={{fontWeight:800,mx:"auto"}}>Magazzino</Typography></Stack><Paper sx={{p:2,mb:2}}><Box sx={{display:"grid",gridTemplateColumns:"2fr repeat(4,1fr)",gap:1}}><TextField label="Cerca pannello, pacco, commessa o cliente" value={search} onChange={e=>setSearch(e.target.value)}/><TextField select label="Commessa" value={order} onChange={e=>setOrder(e.target.value)}><MenuItem value="">Tutte</MenuItem>{options(c=>c.ordine).map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select label="Cliente" value={client} onChange={e=>setClient(e.target.value)}><MenuItem value="">Tutti</MenuItem>{options(c=>c.cliente).map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select label="Camion" value={truck} onChange={e=>setTruck(e.target.value)}><MenuItem value="">Tutti</MenuItem>{Array.from(new Set(commesse.flatMap(c=>c.pannelli.map(p=>p.numeroCamion)))).map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField select label="Tipo unità" value={type} onChange={e=>setType(e.target.value)}><MenuItem value="all">Tutti</MenuItem><MenuItem value="single">Singoli</MenuItem><MenuItem value="package">Pacchi</MenuItem></TextField></Box></Paper>
    {(type==="all"||type==="single")&&<Paper sx={{p:2,mb:2}}><Typography variant="h6">Pannelli singoli disponibili</Typography><Table size="small"><TableHead><TableRow>{["Commessa","Cliente","Camion","Pannello","Master panel","Dimensioni","Peso","Volume","Data scansione","Operatore","Stato",""].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{visibleSingles.map(unit=>{const p=panelFor(unit)!;return <TableRow key={`${unit.commessa}-${unit.camion}-${unit.numeroPannello}`}><TableCell>{unit.commessa}</TableCell><TableCell>{clientFor(unit)}</TableCell><TableCell>{unit.camion}</TableCell><TableCell>{p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)} × {Math.round(p.lunghezza)} × {Math.round(p.altezza)}</TableCell><TableCell>{p.peso.toFixed(1)} kg</TableCell><TableCell>{p.volume.toFixed(3)} m³</TableCell><TableCell>{new Date(unit.chiusaIl).toLocaleString("it-IT")}</TableCell><TableCell>{unit.operatore}</TableCell><TableCell>{p.caricato?"CARICATO":"DISPONIBILE"}</TableCell><TableCell><IconButton color="error" onClick={()=>setPending({kind:"single",unit,blocked:p.caricato})}><DeleteOutlinedIcon/></IconButton></TableCell></TableRow>})}</TableBody></Table></Paper>}
    {(type==="all"||type==="package")&&<Paper sx={{p:2}}><Typography variant="h6" sx={{mb:1}}>Pacchi</Typography>{visiblePackages.map(pack=><Accordion key={pack.codice}><AccordionSummary expandIcon={<ExpandMoreIcon/>}><Box sx={{display:"grid",gridTemplateColumns:"180px repeat(7,1fr) auto auto",width:"100%",alignItems:"center",gap:1}}><b>{pack.codice}</b><span>{pack.commessa}</span><span>{pack.cliente}</span><span>{pack.camion}</span><span>{pack.numeroPezzi} pannelli</span><span>{pack.pesoTotale.toFixed(1)} kg</span><span>{pack.volumeTotale.toFixed(3)} m³</span><span>{pack.stato}</span><Button size="small" startIcon={<PrintOutlinedIcon/>} onClick={event=>{event.stopPropagation();setPrintPack(pack);}}>Stampa etichetta pacco</Button><IconButton color="error" onClick={e=>{e.stopPropagation();setPending({kind:"package",pack,blocked:pack.stato==="CARICATO"||pack.stato==="SPEDITO"});}}><DeleteOutlinedIcon/></IconButton></Box></AccordionSummary><AccordionDetails><Table size="small"><TableHead><TableRow>{["Pannello","Master panel","Dimensioni","Peso","Volume","Operatore / chiusura"].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{pack.pannelli.map(p=><TableRow key={p.numeroPannello}><TableCell sx={{pl:4}}>↳ {p.numeroPannello}</TableCell><TableCell>{p.numeroMasterPanel}</TableCell><TableCell>{Math.round(p.spessore)} × {Math.round(p.lunghezza)} × {Math.round(p.altezza)}</TableCell><TableCell>{p.peso.toFixed(1)} kg</TableCell><TableCell>{p.volume.toFixed(3)} m³</TableCell><TableCell>{pack.operatore} · {new Date(pack.chiusoIl).toLocaleString("it-IT")}</TableCell></TableRow>)}</TableBody></Table></AccordionDetails></Accordion>)}{Array.from(drafts.entries()).filter(([,items])=>items.length).map(([key,items])=>{const [draftOrder,draftTruck]=draftParts(key);const draftCommessa=commesse.find(c=>c.ordine===draftOrder);return <Accordion key={key}><AccordionSummary expandIcon={<ExpandMoreIcon/>}><b>Pacco aperto — {draftOrder} / {draftTruck} ({items.length} pannelli)</b></AccordionSummary><AccordionDetails>{items.map(p=><Box key={p.numeroPannello} sx={{display:"flex",alignItems:"center",pl:3}}><span>↳ Pannello {p.numeroPannello} · MP {p.numeroMasterPanel} · {p.peso.toFixed(1)} kg · {draftCommessa?.cliente}</span><IconButton color="error" sx={{ml:"auto"}} onClick={()=>setPending({kind:"draft",key,panel:p})}><DeleteOutlinedIcon/></IconButton></Box>)}</AccordionDetails></Accordion>})}</Paper>}
    <Dialog open={pending!==null} onClose={()=>setPending(null)}><DialogTitle>{pending&&"blocked" in pending&&pending.blocked?"Operazione non consentita":"Conferma annullamento"}</DialogTitle><DialogContent><DialogContentText>{pending?.kind==="single"?(pending.blocked?"Il pannello è CARICATO o SPEDITO e non può essere eliminato.":"Annullare la scansione del pannello e riportarlo a MANCANTE?"):pending?.kind==="package"?(pending.blocked?"Il pacco è CARICATO o SPEDITO e non può essere annullato.":`Annullare il pacco ${pending.pack.codice} e riportare tutti i pannelli a MANCANTE?`):"Rimuovere il pannello dal pacco aperto?"}</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setPending(null)}>{pending&&"blocked" in pending&&pending.blocked?"Chiudi":"Annulla"}</Button>{!(pending&&"blocked" in pending&&pending.blocked)&&<Button color="error" variant="contained" onClick={confirm}>Conferma</Button>}</DialogActions></Dialog><Dialog fullWidth maxWidth="lg" open={printPack!==null} onClose={()=>setPrintPack(null)}><DialogTitle className="no-print">Ristampa pacco {printPack?.codice}</DialogTitle><DialogContent>{printPack&&<PackagePrintPreview pack={printPack}/>}</DialogContent><DialogActions className="no-print"><Button onClick={()=>setPrintPack(null)}>Chiudi</Button></DialogActions></Dialog><Snackbar open={notice!==null} autoHideDuration={3500} onClose={()=>setNotice(null)}><Alert severity={notice?.severity??"success"} onClose={()=>setNotice(null)}>{notice?.message}</Alert></Snackbar>
  </Box>;
}
